### ISSUE TITLE
OSPO research and analysis workshop 23.03

### ISSUE THREAD

**Issue by jstclair2019** [finos/open-source-readiness#102]
In conjunction with TODO Group, FINOS OSR will participate in a workshop to review research and analysis completed in the field of open source and OSPOs. Results of this workshop will update both OSR and TODO group in best practices, The BOK, and OSMM alignment.

**Comment by caradelia** [comment]
@rhyddian https://todogroup.org/blog/ospo-survey-2022-results/

**Comment by Neetuj** [comment]
I am very interested in this topic and in helping out with this effort
