### ISSUE TITLE
OSPO Maturity

### ISSUE THREAD

**Issue by jstclair2019** [finos/open-source-readiness#105]
In considering the TODO Group guidance on OSPO maturity models and defining our own maturity model, I think we have an opportunity to consider how we harmonize our thinking. 
As suggested, the OSPO maturity model focuses on the OSPO, its structure and activities. However, the OSPO may or may not represent the totality of OS activities and governance. In the FINOS OSMM model, we consider the OSPO as well as other personas and activities.
I think this leaves us with a decision as part of shaping the OSMM and working with TODO:
1) Continue to shape the OSMM as an "OSPO-centric model" , meaning an organization with a high OSPO maturity inherits a high organizational maturity, and OS is focused on OSPO activities. (i.e "everything open source happens in the OSPO")
2) The OSPO maturity is a subset of the OSMM. In this model, The OSPO maturity is a *subset* of the organization's maturity. It would be expected that the OSPO has achieved a high level of maturity to support an OSMM level 3 or better, but doesn't constitute all of the necessary activities for an OSMM level 4 or 5.

**Comment by robmoffat** [comment]
I think option 2.   Also, this would apply to individuals too.   A developer (say) could be working at an organisation with a maturity of Level 2, but if they run their own open source project on the side and manage a community of contributors on it, perhaps they are at a personal Level 4?

**Comment by jstclair2019** [comment]
> I think option 2. Also, this would apply to individuals too. A developer (say) could be working at an organisation with a maturity of Level 2, but if they run their own open source project on the side and manage a community of contributors on it, perhaps they are at a personal Level 4?

Right, so a Level 1 Ad hoc organization starts an OSPO and hires level 4 OS developers. Good thinking.

**Comment by robmoffat** [comment]
Renamed comment, based on the rest of the work going on around this and discussion yesterday.  We need to talk with TODO about what constitutes a "mature" OSPO in order to build out a checklist.

**Comment by robmoffat** [comment]
I don't think we're going to come back to this.
