### ISSUE TITLE
1st March 2023 - Open Source Readiness Meeting Agenda

### ISSUE THREAD

**Issue by psmulovics** [finos/open-source-readiness#107]
## Date
Wednesday 1st March 2023 - 2pm GMT / 10am ET

## Untracked attendees
- Fullname, Affiliation, (optional) GitHub username
- ...

## Meeting notices
- FINOS **Project leads** are responsible for observing the FINOS guidelines for [running project meetings](https://community.finos.org/docs/governance/meeting-procedures/). Project maintainers can find additional resources in the [FINOS Maintainers Cheatsheet](https://community.finos.org/docs/finos-maintainers-cheatsheet).

- **All participants** in FINOS project meetings are subject to the [LF Antitrust Policy](https://www.linuxfoundation.org/antitrust-policy/), the [FINOS Community Code of Conduct](https://community.finos.org/docs/governance/code-of-conduct) and all other [FINOS policies](https://community.finos.org/docs/governance/#policies). 

- FINOS meetings involve participation by industry competitors, and it is the intention of FINOS and the Linux Foundation to conduct all of its activities in accordance with applicable antitrust and competition laws. It is therefore extremely important that attendees adhere to meeting agendas, and be aware of, and not participate in, any activities that are prohibited under applicable US state, federal or foreign antitrust and competition laws. Please contact legal@finos.org with any questions.

- FINOS project meetings may be recorded for use solely by the FINOS team for administration purposes. In very limited instances, and with explicit approval, recordings may be made more widely available.

## Agenda
- [x] Convene & roll call (5mins)
- [x] Display [FINOS Antitrust Policy summary slide](https://community.finos.org/Compliance-Slides/Antitrust-Compliance-Slide.pdf) 
- [x] Review Meeting Notices (see above)
- [ ] Approve past meeting minutes
- [x] Maturity level PRs #103 @robmoffat 
- [x] Bio page #106 @robmoffat
- [x] Appeal for article writers 
- [x] Personas work
- [x] Next roundtable: Potential topics: Training, DLP discussion- any other suggestions?
- [ ] AOB, Q&A & Adjourn (5mins)

## Decisions Made
- [ ] Decision 1
- [ ] Decision 2
- [ ] ...

## Action Items
- [ ] Action 1
- [ ] Action 2
- [ ] ...

### Zoom Details
- https://zoom.us/j/99753528440?pwd=OEFPWkQzLy9hWlV4NmM0RC9VRjhwQT09
- **Meeting ID:** 997 5352 8440
- **Passcode:** 987996

### Join by Phone
- Find your local number: https://zoom.us/u/adl5rhui4P

**Comment by robmoffat** [comment]
Some potential topics for article writers:

### Level 1 (Usage)
Understanding Open Source Licensing (Developers)
Evaluating Software Dependency Risks
ROI
Support
Maturity
Understanding Inbound Security Risks

### Level 2 (Conformance)
Open Source Inventory
License Compliance Management (OSPO)
Vulnerability Testing
Security : keeping dependencies up-to-date https://openssf.org/resources/guides/
Legislation: CRA etc.

Training: 
Developer Training on the above 2 levels

### Level 3 (Culture and Ecosystem)
Creating an OSPO
Open Source Policy- what is one, why it’s needed, how it’s created.  Things that are in it, examples of parts of it.  - PS to draft
Inner source/ Licensing
DLP Strategies
CLAs + DCOs
Metrics - break these out? we need to document some. -JIM
Forking: Internal / External / Pull Requests (somewhat written)
Outbound Security Risks
How to start contributing
Reference Tool Set

Training:
Developer Training on the above
OSPO Training on the Above

###  Level 4: Engagement and Hosting
Publishing Open Source (licensing implications of, chargebacks, security, dodgy commits, repojacking etc. 
Vulnerability Disclosure
Foundations and Community (events, ambassadors etc)
Talent:  Open Source career paths, incentivising, ambassadors, recognition - JIM

Training:
Developer Training on the above
OSPO Training on the Above
Exec Training on the Above

###  Level 5: Strategic
Open Source Strategy:  what is one?  how to create one.

Training
OSPO Training on the Above
Exec Training on the Above


Upside RIsks/Goals/Advantages

Interoperability
Accessibility
Open Data
Transparency
Testability
Privacy/Security/Data Protection

**Comment by caradelia** [comment]
@psmulovics thinking we move up "personas work" to after appeal for article writers and do a 15-20 min "workshop" of a persona.

**Comment by jstclair2019** [comment]
I like the metrics and career path topics. Those have come up in TODO group and others.

**Comment by caradelia** [comment]
👋 Cara Delia / RedHat

**Comment by ColinEberhardt** [comment]
👋  / Scott Logic

**Comment by psmulovics** [comment]
Peter Smulovics / Morgan Stanley

**Comment by jstclair2019** [comment]
Jim St.Clair/FINOS

**Comment by katnovakovic** [comment]
Katrina Novakovic / Citi

**Comment by psmulovics** [comment]
Added first draft of "Open Source Policy- what is one, why it’s needed, how it’s created. Things that are in it, examples of parts of it. " to BoK draft
