### ISSUE TITLE
Add chair/co-chair job description & related documentation

### ISSUE THREAD

**Issue by vmbrasseur** [finos/open-source-readiness#12]
A few of us have been working on this in a Google Doc. We need to get it moved to documentation in the SIG repo.

**Comment by vmbrasseur** [comment]
I was about to work on this but decided to wait for the resolution of #16. That'll help me decide where best to put this sort of governance documentation.

**Comment by psmulovics** [comment]
@vmbrasseur , can I somehow get access to the Doc mentioned above?
