### ISSUE TITLE
Documentation for Leveraging Open Source as Strategy

### ISSUE THREAD

**Issue by gyehuda** [finos/open-source-readiness#144]
### Description of Problem:
We need a page for OSMM Level 5

### Potential Solutions:
Proposing text that addresses a few approaches to open source and strategy.
One approach is to explain how running an OSPO improves the way in which you can address strategy.
An additional approach is how having open source capabilities enable you to make better buy/build decisions.

We may want to select one approach, or perhaps add a third.

**Comment by robmoffat** [comment]
Implemented by:

 - #145
