### ISSUE TITLE
7 June 2023 - Open Source Readiness Meeting Agenda

### ISSUE THREAD

**Issue by psmulovics** [finos/open-source-readiness#146]
## Date
7 June 2023 - 10am EST / 3pm GMT

## Untracked attendees
- Fullname, Affiliation, (optional) GitHub username
- ...

## Meeting notices
- FINOS **Project leads** are responsible for observing the FINOS guidelines for [running project meetings](https://community.finos.org/docs/governance/meeting-procedures/). Project maintainers can find additional resources in the [FINOS Maintainers Cheatsheet](https://community.finos.org/docs/finos-maintainers-cheatsheet).

- **All participants** in FINOS project meetings are subject to the [LF Antitrust Policy](https://www.linuxfoundation.org/antitrust-policy/), the [FINOS Community Code of Conduct](https://community.finos.org/docs/governance/code-of-conduct) and all other [FINOS policies](https://community.finos.org/docs/governance/#policies). 

- FINOS meetings involve participation by industry competitors, and it is the intention of FINOS and the Linux Foundation to conduct all of its activities in accordance with applicable antitrust and competition laws. It is therefore extremely important that attendees adhere to meeting agendas, and be aware of, and not participate in, any activities that are prohibited under applicable US state, federal or foreign antitrust and competition laws. Please contact legal@finos.org with any questions.

- FINOS project meetings may be recorded for use solely by the FINOS team for administration purposes. In very limited instances, and with explicit approval, recordings may be made more widely available.

## Agenda
- [x] Convene & roll call (5mins)
- [x] Display [FINOS Antitrust Policy summary slide](https://community.finos.org/Compliance-Slides/Antitrust-Compliance-Slide.pdf) 
- [x] Review Meeting Notices (see above)
- [ ] Approve past meeting minutes
- [x] Welcome Thomas Cooper (RBC) as OSR Co-Lead
- [x] Review PR #141 
- [x] Review Parts of #135 - Labour, Cyber Security, Communications, Surveillance
- [x] Talk about status of:  #128, #140 #145 to merge for the upcoming members meeting
- [x] AOB, Q&A & Adjourn (5mins)

## Decisions Made
- [ ] Decision 1
- [ ] Decision 2
- [ ] ...

## Action Items
- [ ] Action 1
- [ ] Action 2
- [ ] ...

### Zoom Details
- https://zoom.us/j/99753528440?pwd=OEFPWkQzLy9hWlV4NmM0RC9VRjhwQT09
- **Meeting ID:** 997 5352 8440
- **Passcode:** 987996

### Join by Phone
- Find your local number: https://zoom.us/u/adl5rhui4P

**Comment by thomascooper-rbc** [comment]
Thomas Cooper, RBC 👋🏻

**Comment by psmulovics** [comment]
Peter Smulovics / Morgan Stanley 🏦

**Comment by pholleran** [comment]
Phil from GitHub here 👋

**Comment by robmoffat** [comment]
Rob / FINOS 🐄

**Comment by gyehuda** [comment]
Attending. I work at at a bank in the U.S.

**Comment by BrittanyIstenes** [comment]
Brittany Istenes - Fannie Mae

**Comment by HelloKay27** [comment]
Kay XiongPachay / Goldman Sachs

**Comment by eminty69** [comment]
Elspeth Minty / RBC

**Comment by robmoffat** [comment]
# Minutes

Agenda: [https://github.com/finos/open-source-readiness/issues/146](https://github.com/finos/open-source-readiness/issues/146)

See issue for attendees, + Maria

## Notes / Action Items

Elspeth Minty / Thomas Cooper:  EM is handing over co-lead work to TC. He is the RBC OSPO. 

PS: =  Member Meeting: happening next week.  We would like to get the PRs merged before the member meeting.

**PR 141:  **

PS: Originally from a post, explaining why to open source a project.  All based on the idea that platforms should be pluggable.  Publishing your interfaces allows people to build an ecosystem.  Four reasons why you’d want to do this.

TC: Around staff retention - do we have a spot to talk about general benefits of open source?  

RM/PS: This is in Making-the-case article

GY: Not fixing in the upstream is an anti-pattern.  Even if you want to be as regressive as possible, you still need to push upwards.  

RM: Rhyddian has put some statistics around this - it’s a shocking waste.

PC: Can we get these stats ?

RM: We should ask Rhyddian at the member meeting

PC: Can we get some more tangible guidance around attracting talent?  

PS: We don’t have much right now.  

RM: Converse argument is hiring people who are maintainers and therefore you are improving the project and getting talent at the same time.

PC: Are there any other arguments?

RM: Firm reputation heavily influenced by open source

KX: Document how to create a clear call-to-action from the community.  

Can we also add https://ithandbook.ffiec.gov/it-booklets/architecture-infrastructure-and-operations/v-infrastructure/vc-software/vc2-software-types/vc2-a-open-source-software/ and comparable regulations that may apply?

Thomas Cooper to Everyone (15:30)

our canadian regulator (OSFI) has an equivalent set of guides: [https://www.osfi-bsif.gc.ca/Eng/fi-if/rg-ro/gdn-ort/adv-prv/Pages/icrt-tcfr.aspx](https://www.osfi-bsif.gc.ca/Eng/fi-if/rg-ro/gdn-ort/adv-prv/Pages/icrt-tcfr.aspx)

**Level 3 PR #135**

TC - no distinction between personal and firm, everything is includes.

KX - we log all firm and side projects.  You can’t interact with any project until you have approval.  

PS - GitHub terms say you shouldn’t have different GitHub accounts for these things.

PH Also the user owns the account, even if they leave the firm.  This is a ToS violation.  There isn’t any extra security or monitoring capability around that.

KX We use personal/firm emails for signing the commits differently depending on the type of contribution

PH  I am still asking GitHub to improve this.  You can make the PR from your firm’s GitHub org, or you can add the firm details to the commit message.

RM The second one sounds like a lot of work.

TC GitHub enterprise login and public GitHub are very different and the IDs don’t match up.

PS - We should have the two-github-ids approach be an anit-pattern

MW - can we just be clear about what an organisation is to do then?

RM / KX - 1. Get the user’s GitHub Id.  Track their interactions.  Look at the projects they are involved in.  Some firms then categorize as personal/firm, others just consider everything as firm business.  

KX - Staff need approval.  They have to answer about 5 questions before a project can be designated one way or another and they are allowed to interact with it.

PH - Is it unusual in these claims over their staff?

PS/RM No, it’s a normal assertion of firm copyright

PH - Issue participation is more of a challenge than PRs/Commits - you can use GitProxy for that.

PS - Our firm asserts everything. Joining an OSS project is a bit like attending a political rally.  You are part of it and you’re an employee, so therefore the firm is there.

**Gills PR #145**

Looking at the maturity levels, - level 5 is strategy.  _How your success in running an OSPO helps your organisation deal with strategy.  _

Landscape, climate, you can’t control. But in chess, you can move some pieces.

But - with an OSPO you’re adding extra moves that you couldn’t do before.  You have extra strategic options.  

But, the notes were _other_.  

RM: yes, this is the right idea.  We should also talk about selling this to people in the organisation.

GY:  Should this be bullets, or a blog?

PS: I’ve re-written mine to make ti more in the style of the OSPO.

GY: Buy-vs-build is the old way.  OS Orgs are able to try an augmented way.

TC: This is quite compelling content.  I wonder if strategy evolves throughout the maturity model.  THe opportunities it unlocks.

GY: Simon Wildley’s book is inspiring this. I’ll add a footnote to acknowledge this.

PS: We’re not trying to write everything, but we want to catalog.  

GY: Will add more details (buy vs build), and any other things please send them my way.
