### ISSUE TITLE
21 June 2023 - Open Source Readiness Meeting Agenda

### ISSUE THREAD

**Issue by psmulovics** [finos/open-source-readiness#150]
## Date
21 June 2023 - 9am EST / 2pm GMT

## Untracked attendees
- Fullname, Affiliation, (optional) GitHub username
- ...

## Meeting notices
- FINOS **Project leads** are responsible for observing the FINOS guidelines for [running project meetings](https://community.finos.org/docs/governance/meeting-procedures/). Project maintainers can find additional resources in the [FINOS Maintainers Cheatsheet](https://community.finos.org/docs/finos-maintainers-cheatsheet).

- **All participants** in FINOS project meetings are subject to the [LF Antitrust Policy](https://www.linuxfoundation.org/antitrust-policy/), the [FINOS Community Code of Conduct](https://community.finos.org/docs/governance/code-of-conduct) and all other [FINOS policies](https://community.finos.org/docs/governance/#policies). 

- FINOS meetings involve participation by industry competitors, and it is the intention of FINOS and the Linux Foundation to conduct all of its activities in accordance with applicable antitrust and competition laws. It is therefore extremely important that attendees adhere to meeting agendas, and be aware of, and not participate in, any activities that are prohibited under applicable US state, federal or foreign antitrust and competition laws. Please contact legal@finos.org with any questions.

- FINOS project meetings may be recorded for use solely by the FINOS team for administration purposes. In very limited instances, and with explicit approval, recordings may be made more widely available.

## Agenda
- [x] Convene & roll call (5mins)
- [x] Display [FINOS Antitrust Policy summary slide](https://community.finos.org/Compliance-Slides/Antitrust-Compliance-Slide.pdf) 
- [x] Review Meeting Notices (see above)
- [x] Approve past meeting minutes
- [x] Recap on the Member Meeting by @robmoffat  (@caradelia 's session, @robmoffat 's Presentation, @chamindra 's Inner Source Presentation)
- [x] @psmulovics 's upcoming blog post
- [x] Supply Chain Security - overview of what's been discussed on their 6/20 meeting
- [x] AOB, Q&A & Adjourn (5mins)

## Decisions Made
- [ ] Decision 1
- [ ] Decision 2
- [ ] ...

## Action Items
- [ ] Action 1
- [ ] Action 2
- [ ] ...

### Zoom Details
- https://zoom.us/j/99753528440?pwd=OEFPWkQzLy9hWlV4NmM0RC9VRjhwQT09
- **Meeting ID:** 997 5352 8440
- **Passcode:** 987996

### Join by Phone
- Find your local number: https://zoom.us/u/adl5rhui4P

**Comment by pholleran** [comment]
👋 - Phil from :octocat:

**Comment by mimiflynn** [comment]
Mimi Flynn / Morgan Stanley

**Comment by robmoffat** [comment]
Rob / FINOS 🦙

**Comment by psmulovics** [comment]
Peter Smulovics / Morgan Stanley 🏢

**Comment by HelloKay27** [comment]
Kay XiongPachay / Goldman Sachs

**Comment by temenos-labs** [comment]
Ben Davolls - Temenos

**Comment by robmoffat** [comment]
## Minutes

- RM gave an overview of the members meeting, talking about [his presentation about OSR](https://osr.finos.org/docs/osr-resources/Presentation), Chamindra's InnerSource license talk and [Cara's Personas Roundtable](https://docs.google.com/document/d/1FiMgMdEaC5oqAXtHHf7G1SxGX3U3wFEoYi5C3yYttVw/edit)
 - PS talked about producing a blog article based on the Personas Round Table (see above)
 - PS and RM gave an overview of the newly-formed Supply Chain Security Working Group, and how this would feed into OSR.

### Certifications

- RM showed the [OSR Certification Straw Man](https://docs.google.com/document/d/1HgGg2lY3IDKP07uOS4CQTdfd_FUn5dnkc3uq-zTpF7I/edit), which is 
 > The FINOS / TODO Certified Open Source Developer exam is designed for developers contributing to open source projects whilst  working in financial institutions internationally. 

- KN suggested that this was too large for a single exam, and that it should be split into two parts - consumption and contribution.  
- KX, BI said that for something like **social media usage** we need to be careful that different firms have different stances on this, and that obviously makes a difference to what questions you could ask
- MF and PS talked about _who_ might take the exam, and whether day traders might take it - is that a problem?
- RM said that they could always do that, but they would have to pay for it.  FINOS expects to charge for the exam, probably giving out free seats to Gold and Platinum members (details to be figured out later)
- KX asked about which courses would be pre-requisites for the exam and whether we would expect people to have experience with Git etc. beforehand. 
- PS asked whether we needed to test on GitHub, might be better to just ask people to take a crash course.
- RM talked about how William Rothwell had done some work filtering the training for UBS, and that he was also taking LFcourses to see which ones were relevant.  
- KX said a course around working groups would be handy, as it's hard to know up-front how to work with them.  Best practices of this.
- RM / BI agreed this should also be part of the "Working With Foundations" article that BI is writing.
- KX said "Ethical AI" might be too much - a whole course on it's own!

### Policy

- MH talked about the contribution policy talk that Jamie Slome did at the Member Meeting, and how they had some good ideas about how to describe the different roles, and how to avoid "vanity" open source projects.
- RM said he would try and get Jamie to attend the next meeting to present this to the OSR group.

**Comment by robmoffat** [comment]
## CIti Contribution Policy

KN - Showing the citi/citi-ospo repo

KN - this focuses just on contribution guidelines.  Discussed the difference between FOSS and OSS… but this is just terminology.

(asks for questions)

GY - Bravo, fantastic.  Very impressive.  Both comprehensive and succinct.  Would love to know the backstory behind getting this reviewed and approved. 

KN - To get this internally published, I wasn’t involved from the start, but it was a lot of work.  One person championing this, reaching out to all the parts of the organisation.  Wanted to make thai a global policy, which meant reaching out globally.  Dev led, but we needed to get not just the tech people but also involve HR, Legal, Heavily ECOM and Social Media.  Had to look at existing policies and see how they applied, get their buy in and see how they appplied to open source. 

KN- One crucial distinction is company business vs non-company business.  This was crucial to getting thighs approved.  Everyone was supportive but worried about regulations.  There were lots of case-by-case use-cases that we considered and checked the policy.

KN - Developers were scared.  Clarifying the policy for developers was important.  Can we mention the word “citi”?  You have to know what’s in the public domain vs what’s private.

GY - Also, the policy contains MUST - but this means there needs to be a control.  Can we talk about the degree of controls for each assertion?  How do we demonstrate compliance to that obligation?

KN - With the guidelines, some things are vague, such as “OSPO Approved Tools” - we don’t want to have to keep updating that!  How can we enforce controls?  A lot of the time by tools.  You also have to take training.  We track access requests with tools.  We add as many controls as we can.

JS - I’m the operations lead for Citi’s OSPO. With regard to must, the implication here is for us that we can map out the requirements for our tools.  The policy’s MUSTs say what the controls are going to be via the tools. E.g. commits MUST use @citi.com, - we can mandate this but where we want to be is to implement this in a control (Via a tool).

MH - I attended JS’s talk.  The categories are slightly different in the tool vs the policy.  

JS - Sponsor is a role - an individual who gives backing to “company moderated” or “interest major” project.

KN - The idea is that if you’re going to contribute or be part of a foundation, there’s a cost in time or money.  The sponsor should be giving the money to do it properly.  We don’t want a half-effort.

KN - On Categories: There are various scales of contribution.  After looking at the types of scenarios, we came up with 4 categories: company moderated, company interest (major and minor) and personal.  

KN - We just keep a list of the first three categories

MH - is there a potential conflict of interest around personal contributions?

JS - We can usually take a position where we look at the contribution and see if it’s a bug fix.  

GY - Note: I really like the categories that Citi has. They remind me of the categorization that I had at a previous company. I don't know if you were inspired by these, but these were the 4 that I used. [https://yahoo.github.io/oss-guide/docs/promoting/support.html](https://yahoo.github.io/oss-guide/docs/promoting/support.html)  The 4 categories above (strategic, limited, minimal, archived) referred to the 4 types that we hosted on our OSPO's github page. But the categories seem to match the way an OSPO would see projects that an employee would contribute to.

JS - If they’re contributing personal, can we delineate the company work?  We definitely inventory all the activity. 

RM - what about outside contributions , done from home?

JS - much larger data leakage from internal contributions.  There shouldn’t be PI there.  They can contribute either way.

AM - how long does it take to approve a contribution?

JS - we should be looking at 1-2 weeks for a bugfix, but it should come down to moments, really.   For an internal project being open sourced, it takes a lot longer.  We’re still getting better at this.  We have to scour the codebase in those cases.  We need to meet the obligations but not scare off developers.

KN - this is just for the initial setup.  After that, it’s just peer-reviews.

AM - lets’ say you have IT vendors.  Does this apply to them too?

KN - This is very citi-specific.  The guideline is just for citi employees.  

Viquar Hashmi - Is our policy similar to other banks?

PS - They are different. It’s a good thing there is no one-size-fits-all.  

GY - this is more progressive relative to banks, less than tech co’s.  Some banks are extraordinarily risk averse. I’ve worked in both environments.  This is forward thinking but also strikes a balance.

KN - we get push back. “What if this goes wrong?” A lot of the risks apply without the policy.

GY - not contributing the bug fix means a fork, which could be better or worse.  Do you see a point where it’s not permission to fix upstream but _demanding._

KN - People are hesitant to commit.  They don’t want to get in trouble.

MH - more a pushback to say, you shouldn’t do something.  We need this documented to pave the way.  

JS - There are a lot of risks for not contributing.  

PC - Question around incentivising.  It takes a while to get approved. How do you incentivize waiting for this?  

JS - Broadly, we’re thinking about taking our compliance to the developer.  We need to make the developer aware, first.  Can we do this in their terminal?  We need to make this part of their existing workflow.  If you have to wait 20 days to push, that’s not ideal.  

KN - There’s a certain kind of profile of people who are willing to contribute, the early adopters.  

MH - One point I’ve considered is volunteering.  OSS contribs could be classified that way.

VH - On the machine learning front, contributing.

EM - For some people this is part of their jobs.  A bug might be required for their job.  It shouldn’t be a spare time thing.

PC - Subsequent contributions are easy: what’s the _initial setup?_

KN - Request to OSPO, reasons, approval from line manager.  New projects need a foundation approval.  E.g. FINOS etc.  Foundations must be approved first and a foundation owner assigned.  Devs then focus on code contribution.

PC- Is this for every project?

KN - Yes.  We generally see requests from whole teams.  It’s easier to onboard 2nd/3rd team to a pre-approved project.

RM - Your policy works around other policies.  Can you talk about that, esp. ECOM?

KN - Every firm has ECOM regulations.  Determining what is company business and what isn’t is important.  If you can rule out a number of projects from being company business, you’re ok.   Rule is : never discuss company business in any open source project.

MH - We’ve adopted something similar.  We haven’t got through the Slack/JIRA Issues thing yet.  How did you get this through the ECOM Team?

KN - People are still worried about this, and so they’re avoiding the slack channels for now. A lot of this comes down to common sense.  Employees are asking their managers.

MH - So, people are allowed on Slack?

KN - Not within Citi.

MH - So, personal accounts only then.

RM - There’s a ‘must’ there around checking communications.

JS - this might be too much work - but there might be something we could do to surveil this.  E.g. how many times an internal URL got mentioned.  We could figure out a baseline for this.

KN - Attending working groups is fine. Speaking - we try to get someone else on the call too, to make sure there is monitoring.

AM - How do you categorize projects?

KN - One off, or on-going? There’s a whole load of criteria.  

JS - If we let devs make contributions first, write the code, then we can start saying what we think is minor or major.  For interest “major”, (adding new files, probably).  At the moment, decided by the OSPO, then we’ll build the controls to decide this.
