### ISSUE TITLE
06 Sept 2023 - Open Source Readiness Meeting Agenda

### ISSUE THREAD

**Issue by robmoffat** [finos/open-source-readiness#170]
## Date
20230906 - 3PM BST, 10AM EST

## Untracked attendees
- Fullname, Affiliation, (optional) GitHub username
- ...

## Meeting notices
- FINOS **Project leads** are responsible for observing the FINOS guidelines for [running project meetings](https://community.finos.org/docs/governance/meeting-procedures/). Project maintainers can find additional resources in the [FINOS Maintainers Cheatsheet](https://community.finos.org/docs/finos-maintainers-cheatsheet).

- **All participants** in FINOS project meetings are subject to the [LF Antitrust Policy](https://www.linuxfoundation.org/antitrust-policy/), the [FINOS Community Code of Conduct](https://community.finos.org/docs/governance/code-of-conduct) and all other [FINOS policies](https://community.finos.org/docs/governance/#policies). 

- FINOS meetings involve participation by industry competitors, and it is the intention of FINOS and the Linux Foundation to conduct all of its activities in accordance with applicable antitrust and competition laws. It is therefore extremely important that attendees adhere to meeting agendas, and be aware of, and not participate in, any activities that are prohibited under applicable US state, federal or foreign antitrust and competition laws. Please contact legal@finos.org with any questions.

- FINOS project meetings may be recorded for use solely by the FINOS team for administration purposes. In very limited instances, and with explicit approval, recordings may be made more widely available.

## Agenda
- [ ] Convene & roll call (5mins)
- [ ] Display [FINOS Antitrust Policy summary slide](https://community.finos.org/Compliance-Slides/Antitrust-Compliance-Slide.pdf) 
- [ ] Review Meeting Notices (see above)
- [ ] Approve past meeting minutes
- [ ] OSFF - Booth + more
- [ ] #156 COSD Certification (item Writing and reviewing, learning paths
- [ ] Open Source Contribution in Finance" (LFD137) Progress
- [ ] [Maturity Models for OSR / BoK](https://docs.google.com/document/d/1ps8_x4-FgVNSkD2rlvGM733mJD4CifZkd5AZMry1Lzo/edit)
- [ ] "FINOVATION" - Book Discussion / Preview
- [ ] ...
- [ ] AOB, Q&A & Adjourn (5mins)

## Decisions Made
- [ ] Decision 1
- [ ] Decision 2
- [ ] ...

## Action Items
- [ ] Action 1
- [ ] Action 2
- [ ] ...

### Zoom Details
- https://zoom.us/j/99753528440?pwd=OEFPWkQzLy9hWlV4NmM0RC9VRjhwQT09
- **Meeting ID:** 997 5352 8440
- **Passcode:** 987996

### Join by Phone
- Find your local number: https://zoom.us/u/adl5rhui4P

**Comment by BrittanyIstenes** [comment]
Brittany Istenes - FNMA

**Comment by kborchers** [comment]
Kris Borchers - GM Financial

**Comment by katnovakovic** [comment]
Katrina Novakovic - Citi

**Comment by eminty69** [comment]
Elspeth Minty / RBC CM

**Comment by mimiflynn** [comment]
Mimi Flynn / Morgan Stanley

**Comment by robmoffat** [comment]
# September 6th 2023


### OSFF Booth:



* **BI**:  Shifts.  Would be good to see who could staff the booth, and figure out shifts. 
* Discussed as things we need: Laptop for slides.   Handouts.  Swag.  Printing out body of knowledge.  QR codes for everything.  Taking the training live is a bit hard!  QR codes over paper.  Posters with QR codes.  E.g maturity model.  Poster with QR codes and topics.  URL under the QR codes.   Suggestion box.  
* **KN**: People might wonder what happens at the working group,  Invite them to participate.  People to attend to talk about particular topics. BI: we’re going to have special guests for inner source.  Once we get the meetings sorted out. 
* **EM**:  Movie trailers?
* **RM: **that sounds like a lot of work…


### Certification & Training

RM described how the certification was going - syllabus is written and weightings for topics agreed.  Item writing kick-off on Friday.  Everyone welcome.  Topics broken down in [https://github.com/finos/open-source-readiness/issues/123](https://github.com/finos/open-source-readiness/issues/123)

RM talked about the finished training being handed to LF - in a few week’s they’ll have something ready for us to preview and try out.

RM explained how the learning path PR worked in Docusaurus.


### Maturity Models:

**RM** talked about OW2, TOOD models, Wipro’s Open Source Maturity model survey.  The BoK uses the first two.  It would be nice if the OSMMS was consistent and integrated with the BoK.

**VL**:  Working in other areas using maturity models.  

**TS**: spent a long time working on a MM for TODO.  

**RM**: We heavily based what we’re doing on the mind map from TS.

**TS**: this is kind of on (his next four month) todo list, so we should talk more about this.  I’d like to open source something to link all the materials.  

**VL**:  would be good to definea  scope.  Can we fgiure out the business value?  What’s the value of a higher maturity?

**VL**: Why is an OSPO strategic?  Can you start there?

**TS**: Did work on the business value of OSPOs.  Organising with Ana the Ospology live.. All are struggling with business value.   

**TS**: Most OSPOs I see don’t try and measure business value.

**Action:** RM/VL/TS - kick off meeting action,


### Book:

**RM** explained the idea of publishing the BoK as a book, and crediting all the authors of the articles that have been written.  Extra materials would be required and the ones we have currently would need to be really polished up.   \
RM said he had a meeting with TODO group tomorrow to find out how their book was going.  

RM I don’t know at this point the process of publishing a book in the LF.

**EM**:  It’s a huge amount of work.

**RM**: Yes, a bit of a stretch goal!

**Comment by psmulovics** [comment]
As a swag - do you think we can get the stickers? It was promised for OSFF'22 NYC but the vendor was late with delivery.
