### ISSUE TITLE
Trailing slash in osr.finos.org breaks all links

### ISSUE THREAD

**Issue by maoo** [finos/open-source-readiness#185]
While browsing on https://osr.finos.org/docs/bok/activities/level-3/making-the-case/#worsened-risk-position-1 I realised that all links were broken.

This is caused by the fact that links are expressed with relative path, for example, in https://github.com/finos/open-source-readiness/blob/main/docs/bok/Activities/Level-3/Making-The-Case.md you'll find:
```
<BoxOut title="Operational Risk" image="/img/bok/risks/operational-risk.png"  link="../../Risks/Operational-Risk" linkText="Operational Risk Details">
```

I'd suggest to define the `trailingSlash` option in `docusaurus.config.js` (see https://docusaurus.io/docs/api/docusaurus-config#trailingSlash ) and make sure that the Docusaurus build fails on broken links, by setting [onBrokenLinks](https://docusaurus.io/docs/api/docusaurus-config#onBrokenLinks) to `throw`.

FYI @TheJuanAndOnly99 - I believe this is happening on other FINOS website, so let's a) put a a pin on this and b) update https://project-blueprint.finos.org

**Comment by psmulovics** [comment]
This is actually part of a bigger issue we have been facing with draft articles, and the reason we had to switch off onBrokenLinks. So if you have draft articles that would link between each other, onBrokenLinks fail - as draft articles are not generated as part of the netlify builds, and not visible, but the links still getting checked. On the other hand, we would love to see draft articles in the netlify builds, but we cannot as we haven't found a way to differentiate between when netlify builds the PR build vs when it does the final build after merge (if it does a new build at all or just flips the existing DNS to the new one? not sure how it works). So yes, we are actually aware of this issue, and it has been chasing us and keeping us up at night, but haven't found a good solution for it yet.

**Comment by maoo** [comment]
Thanks for the answer @psmulovics !

I understand the challenge for `onBrokenLinks`, and I just noticed that it's set to `log`, so at least we can run a `docusaurus build` to get a list of (allegedly) broken links.

However, the `trailingSlash` issue still persists, and it's present right now in production; not sure if you played with this configuration option already; if not, I'll try to make some time this week.

**Comment by psmulovics** [comment]
My problem is, that as BoxOut is a custom MDX control, the links in its link tag won't be checked even if you enable onBrokenLinks to throw :(

**Comment by maoo** [comment]
@psmulovics - the problem is not on `onBrokenLinks`.

The problem - right now - on osr.finos.org, is that web pages are rendered out with or without a trailing slash; however, if a trailing slash is present, links are broken; you can reproduce the issue as follows:
1. Access https://osr.finos.org/docs/bok/activities/level-3/making-the-case/#worsened-risk-position-1
2. Click on first link, DLP Software ; you'll get a 404

Using the `"trailingslash": false` fixed the issue; see https://github.com/finos/open-source-readiness/pull/186

If you open https://deploy-preview-186--open-source-readiness.netlify.app/docs/bok/activities/level-3/making-the-case/#worsened-risk-position-1 you'll notice that the URL gets rewritten to remove the trailing slash, and all links work as expected.

Feel free to merge the PR. TY!
