### ISSUE TITLE
18 October 2023 - Open Source Readiness Meeting Agenda

### ISSUE THREAD

**Issue by psmulovics** [finos/open-source-readiness#187]
## Date
18 October 2023 - 2pm GTM / 9 am EST

## Untracked attendees
- Fullname, Affiliation, (optional) GitHub username
- ...

## Meeting notices
- FINOS **Project leads** are responsible for observing the FINOS guidelines for [running project meetings](https://community.finos.org/docs/governance/meeting-procedures/). Project maintainers can find additional resources in the [FINOS Maintainers Cheatsheet](https://community.finos.org/docs/finos-maintainers-cheatsheet).

- **All participants** in FINOS project meetings are subject to the [LF Antitrust Policy](https://www.linuxfoundation.org/antitrust-policy/), the [FINOS Community Code of Conduct](https://community.finos.org/docs/governance/code-of-conduct) and all other [FINOS policies](https://community.finos.org/docs/governance/#policies). 

- FINOS meetings involve participation by industry competitors, and it is the intention of FINOS and the Linux Foundation to conduct all of its activities in accordance with applicable antitrust and competition laws. It is therefore extremely important that attendees adhere to meeting agendas, and be aware of, and not participate in, any activities that are prohibited under applicable US state, federal or foreign antitrust and competition laws. Please contact legal@finos.org with any questions.

- FINOS project meetings may be recorded for use solely by the FINOS team for administration purposes. In very limited instances, and with explicit approval, recordings may be made more widely available.

## Agenda
- [ ] Convene & roll call (5mins)
- [ ] Display [FINOS Antitrust Policy summary slide](https://community.finos.org/Compliance-Slides/Antitrust-Compliance-Slide.pdf) 
- [ ] Review Meeting Notices (see above)
- [ ] Approve past meeting minutes
- [ ] Fall cleanup of pending issues #55 #74 #76 #78 #87 #123 #162 #163 #165 #174 #177 #179 - decide whether to close, assign, defer, etc
- [ ] AOB, Q&A & Adjourn (5mins)

## Decisions Made
- [ ] Decision 1
- [ ] Decision 2
- [ ] ...

## Action Items
- [ ] Action 1
- [ ] Action 2
- [ ] ...

### Zoom Details
- https://zoom.us/j/99753528440?pwd=OEFPWkQzLy9hWlV4NmM0RC9VRjhwQT09
- **Meeting ID:** 997 5352 8440
- **Passcode:** 987996

### Join by Phone
- Find your local number: https://zoom.us/u/adl5rhui4P

**Comment by caradelia** [comment]
👋 Cara Delia / Red Hat

**Comment by robmoffat** [comment]
Rob / FINOS 🏯

**Comment by tsteenbe** [comment]
👋  Thomas Steenbergen

**Comment by psmulovics** [comment]
Peter Smulovics / Morgan Stanley 🏦

**Comment by robmoffat** [comment]
Minutes:

- See the linked issues for updates on each of those.
- Also: @tsteenbe discussed his OSCLU Proposal: https://docs.google.com/document/d/1fxGEtqLy-u1NrN5LGEsuS-RV4YdCDZcC3zBE5vtPeyU/edit#heading=h.qoiuulcyta5i
- RM said he would send out an invite for OSR sessions on the day following OSFF, which would take place at Morgan Stanley (1 New York Plaza, 36th Floor, New York, NY 10004, United States)
