### ISSUE TITLE
Docusaurus Theme

### ISSUE THREAD

**Issue by robmoffat** [finos/open-source-readiness#204]
### Description of Problem:

- It would be nice if the site had more appealing graphics.

### Potential Solutions:

- OSR Team to suggest sites they like to produce a "mood board" (please comment below).
- Ideally, sites on docusaurus but anything goes.

**Comment by psmulovics** [comment]
@mimiflynn , any ideas?

**Comment by mimiflynn** [comment]
Definitely need to use AI to generate compelling imagery.

**Comment by psmulovics** [comment]
Sure :D I meant web sites for the mood board.

**Comment by mimiflynn** [comment]
1. https://developer.mozilla.org/en-US/
2. https://angular.dev
3. https://mui.com/base-ui/getting-started/
4. https://www.gatsbyjs.com/docs/

I'll look around for more.

**Comment by psmulovics** [comment]
Website and theming - notes from 11/15/2023 #218 

low barrier of entry
flat images
simple boxes linking to content
 getting started
 who we are
 maturity model/personas
taxonomy
making tags/personas more central
should we call to action people to join the calls?
training/cert visibility
netlify tracking?
community handbook?
joining safely
what does OSR mean?
reading order
curated view based on roles
"practical advice how to implement open source in a new organization"

**Comment by robmoffat** [comment]
Here is a mock-up based on looking at the Gatsby theme, linked above:

![OSR Page Layout 1](https://github.com/finos/open-source-readiness/assets/568673/c7aefdac-807d-41f0-a0e7-716befecbf9d)

Some notes: 

- Using a dark blue as the highlight colour, otherwise most supporting text is in grey.  
- Font is Lexend.  Mainly light and some bold.  We use this in other images in OSR too which is helpful.
- Had a stab at doing some colourful boxes.  Not completely sure if this works.

Here is an attempt at a header image we can use on the front page:

![Open Source Readiness Header Image-5](https://github.com/finos/open-source-readiness/assets/568673/99a8f1e5-f134-467f-b182-ccf57f37a407)

Feedback welcome!

**Comment by mimiflynn** [comment]
Alternatives to 'Body of Knowledge':
- handbook
- guidebook
- guide
- manual
- compendium
- reference book
- how-to

'field guide' would be cute too, but you know, perhaps not exactly descriptive.

**Comment by psmulovics** [comment]
Some more wilder alternatives:
- primer
- repository
- corpus
- canon
- doctrines

**Comment by robmoffat** [comment]
@BrittanyIstenes suggested that we can probably just drop body of knowledge completely.  the OSR website "is" a body of knowledge...

**Comment by psmulovics** [comment]
@BrittanyIstenes , I think you are right - save for a little administration piece around meeting schedules and team members list, etc., the whole site is the BoK.
