### ISSUE TITLE
Open Source Review Board 

### ISSUE THREAD

**Issue by robmoffat** [finos/open-source-readiness#207]
## Feature Request

Write an article describing what this is in the artifacts section

**Comment by BrittanyIstenes** [comment]
I will create a high level article about the roles that are needed within this space, what to expect, how to host these sessions.  I am unable to get into the exact details about what is being done in specific companies, but I can give a high level.
 

Before I start writing this article, please have the community put comments in this ticket about what they want to see in this article to avoid back and forth later down the line. 

 

Personal anticipation completion date - End of January

**Comment by robmoffat** [comment]
Amol from LSEG wrote this part a while back: https://osr.finos.org/docs/bok/Activities/Level-2/Consumption-Compliance#example-control--approval-process-for-using-a-new-software-library

Which covers it a little bit.

We should have a brainstorm in an OSR meeting and see what we can come up with in terms of contents.

**Comment by BrittanyIstenes** [comment]
https://github.com/finos/open-source-readiness/pull/256
