### ISSUE TITLE
15 November 2023 - Open Source Readiness Meeting Agenda

### ISSUE THREAD

**Issue by psmulovics** [finos/open-source-readiness#218]
## Date
15 November 2023 - 9 am EST / 2 pm GMT

## Untracked attendees
- Fullname, Affiliation, (optional) GitHub username
- ...

## Meeting notices
- FINOS **Project leads** are responsible for observing the FINOS guidelines for [running project meetings](https://community.finos.org/docs/governance/meeting-procedures/). Project maintainers can find additional resources in the [FINOS Maintainers Cheatsheet](https://community.finos.org/docs/finos-maintainers-cheatsheet).

- **All participants** in FINOS project meetings are subject to the [LF Antitrust Policy](https://www.linuxfoundation.org/antitrust-policy/), the [FINOS Community Code of Conduct](https://community.finos.org/docs/governance/code-of-conduct) and all other [FINOS policies](https://community.finos.org/docs/governance/#policies). 

- FINOS meetings involve participation by industry competitors, and it is the intention of FINOS and the Linux Foundation to conduct all of its activities in accordance with applicable antitrust and competition laws. It is therefore extremely important that attendees adhere to meeting agendas, and be aware of, and not participate in, any activities that are prohibited under applicable US state, federal or foreign antitrust and competition laws. Please contact legal@finos.org with any questions.

- FINOS project meetings may be recorded for use solely by the FINOS team for administration purposes. In very limited instances, and with explicit approval, recordings may be made more widely available.

## Agenda
- [x] Convene & roll call (5mins)
- [x] Display [FINOS Antitrust Policy summary slide](https://community.finos.org/Compliance-Slides/Antitrust-Compliance-Slide.pdf) 
- [x] Review Meeting Notices (see above)
- [x] We would go through what happened at OSFF – unlike Vegas, we want to share everything 😃
- [x] We would go through our ideas around revitalizing the website!
- [x] We would go through the various BoK drafts and milestones:
   - [x] https://github.com/finos/open-source-readiness/milestone/1
   - [x] https://github.com/finos/open-source-readiness/milestone/2
- [ ] AOB, Q&A & Adjourn (5mins)

## Decisions Made
- [ ] Decision 1
- [ ] Decision 2
- [ ] ...

## Action Items
- [ ] Action 1
- [ ] Action 2
- [ ] ...

### Zoom Details
- https://zoom.us/j/99753528440?pwd=OEFPWkQzLy9hWlV4NmM0RC9VRjhwQT09
- **Meeting ID:** 997 5352 8440
- **Passcode:** 987996

### Join by Phone
- Find your local number: https://zoom.us/u/adl5rhui4P

**Comment by robmoffat** [comment]
Rob / FINOS ✊

**Comment by BrittanyIstenes** [comment]
Brittany Istenes - FNMA

**Comment by HelloKay27** [comment]
Kay / Goldman Sachs

**Comment by psmulovics** [comment]
Peter Smulovics / Morgan Stanley

**Comment by pholleran** [comment]
Phil Holleran / GitHub

**Comment by rhyddian** [comment]
Rhyddian Olds @ Citi

**Comment by JamieSlome** [comment]
Jamie Slome / @citi

**Comment by mimiflynn** [comment]
Mimi Flynn / Morgan Stanley

**Comment by katnovakovic** [comment]
Katrina Novakovic - Citi

**Comment by robmoffat** [comment]
## Minutes:


Brian Doyle - mojaloop foundation (?)  Digital IDs that don’t require anything to remit money.  Wanted to attend FINOS meetings. XD of a non-profit in canada.

RM discussed the OSFF - training, certification, body of knowledge. Panel on contribution in finance with Kay and Phil. How they think about open source.  On YouTuve.  

RO:  discussed how we’ve moved on from 9 OSFF’s ago.  Great day.

PS:  Next day we had OSR meeting at MS.    


### Website

PS: Theme is getting a bit old for OSR website.  What is the information we would like to see? How should the theme drive this?

RM: Also including inner source now.

BI:  Low barrier to entry.  Flat box-images.  Who We are, getting started.  Blooms taxonomy - introducing terms, intermediate, I know this…  Getting started at the top.

PH: A good idea.

RO: Can we link this to the tags?  I’m an OSPO, I’m Legal.

PS:  We tried to do this…

RO: We should move this front and center, key personas

KN:  Do people come to the site and don’t attend the calls?  Might be quite intimidating, to attend a meeting cold with all these compliance people.

RO: training on the main page - this is the key part to start with, it’s more accessible than the BoK.

PS:  What about analytics?  Who accesses this?  Google is disabled from MS, probalby the case for other banks.  Can we have a netlify plugin for analytics.  

CD: Anything from a low barrier to entry.   Highlighted the onboarding, community handbook.  Only thing about funnelling through a persona… you can’t base this on IP… it shouldn’t matter where you come from as to what you want to see.  It would be nice to make the meetings more inclusive - “joining safely - you don’t have to give up secret sauce.”.  

MF - it wasn’t that long ago, but I was just trying to figure out what was even meant by open source “readiness”.  When you’re ready, are you done with it?  Based on handbooks I’ve read recently, we should logically outline the content.    

RO: having a curated view based on roles would be great.  

KN:  “Practical advice on implementing open source in a financial services organization”

RM: showed the milestones for completing BoK and polishing it

RM: talked about marketing of Ttraining and Certification for 2024.
