### ISSUE TITLE
7 February 2024 - Open Source Readiness Meeting Agenda

### ISSUE THREAD

**Issue by psmulovics** [finos/open-source-readiness#234]
## Date
7 February 2024 - 10 am EST / 3pm GMT

## Untracked attendees
- Fullname, Affiliation, (optional) GitHub username
- ...

## Meeting notices
- FINOS **Project leads** are responsible for observing the FINOS guidelines for [running project meetings](https://community.finos.org/docs/governance/meeting-procedures/). Project maintainers can find additional resources in the [FINOS Maintainers Cheatsheet](https://community.finos.org/docs/finos-maintainers-cheatsheet).

- **All participants** in FINOS project meetings are subject to the [LF Antitrust Policy](https://www.linuxfoundation.org/antitrust-policy/), the [FINOS Community Code of Conduct](https://community.finos.org/docs/governance/code-of-conduct) and all other [FINOS policies](https://community.finos.org/docs/governance/#policies). 

- FINOS meetings involve participation by industry competitors, and it is the intention of FINOS and the Linux Foundation to conduct all of its activities in accordance with applicable antitrust and competition laws. It is therefore extremely important that attendees adhere to meeting agendas, and be aware of, and not participate in, any activities that are prohibited under applicable US state, federal or foreign antitrust and competition laws. Please contact legal@finos.org with any questions.

- FINOS project meetings may be recorded for use solely by the FINOS team for administration purposes. In very limited instances, and with explicit approval, recordings may be made more widely available.

## Agenda
- [ ] Convene & roll call (5mins)
- [ ] Display [FINOS Antitrust Policy summary slide](https://community.finos.org/Compliance-Slides/Antitrust-Compliance-Slide.pdf) 
- [ ] Review Meeting Notices (see above)
- [ ] Approve past meeting minutes
- [ ] Victor Lu presentation on Strategy and Maturity
- [ ] AOB, Q&A & Adjourn (5mins)

### Zoom Details
- https://zoom.us/j/99753528440?pwd=OEFPWkQzLy9hWlV4NmM0RC9VRjhwQT09
- **Meeting ID:** 997 5352 8440
- **Passcode:** 987996

### Join by Phone
- Find your local number: https://zoom.us/u/adl5rhui4P

**Comment by eminty69** [comment]
Elspeth Minty - RBC CM

**Comment by robmoffat** [comment]
Rob / FINOS 🐌

**Comment by psmulovics** [comment]
Peter Smulovics / Morgan Stanley

**Comment by chamindra** [comment]
Chamindra de Silva / Citi 👋

**Comment by pholleran** [comment]
Phil Holleran, GitHub

**Comment by pholleran** [comment]
@robmoffat @psmulovics - I'd like to propose an agenda item for the next meeting.

My colleagues over in our OSPO recently released [internal-contribution-forks](https://github.com/github-community-projects/internal-contribution-forks). We'd welcome the opportunity to share a bit about the project with the group, discuss use cases it covers, and those it doesn't.

**Comment by psmulovics** [comment]
@pholleran this seems to fit well the April 3rd topic ( #224 ), @robmoffat , you think we can add it to that session or would there be too much content for one session?

**Comment by pholleran** [comment]
@psmulovics - happy to present where the group thinks it makes the most sense. I don't want to detract from the git-proxy presentation and know that an AMA for me and @ashleywolf had been suggested for March 6, hence my suggestion for the next meeting.

**Comment by robmoffat** [comment]
Sounds good to me?  

I've made a minor update to #224  to reflect this is locked in now
