### ISSUE TITLE
Microsite footer points to old wiki links

### ISSUE THREAD

**Issue by gyehuda** [finos/open-source-readiness#25]
## Bug Report
The microsite footer points to the the older wiki

### Steps to Reproduce:
Visit https://osr.finos.org/docs/resources
click on Community Governance in the footer

### Expected Result:
a page on the microsite

### Actual Result:
you get to https://finosfoundation.atlassian.net/wiki/spaces/FINOS/pages/75530783/Community+Governance+-+ARCHIVED

### Additional Context:
This is the file to be updated https://github.com/finos/open-source-readiness/blob/master/website/core/Footer.js
There are lingering references to the wiki that this group has deprecated. Let's move those all to the microsite.

**Comment by psmulovics** [comment]
I see same problem regards Community Handbook. Thank you for noting.

**Comment by psmulovics** [comment]
I propose the following URLs:

- https://www.finos.org/governance for the Community Governance and rename the link to Governance
- Removing the other URL

**Comment by psmulovics** [comment]
@mcleo-d , @vmbrasseur , you OK with the proposal?

**Comment by vmbrasseur** [comment]
I'm a big 👍 on the first URL but don't feel I have enough context for the second to answer. At the very least that href name will need to change to reflect the actual contents of the document.

Is this a footer that's shared across all FINOS SIG microsites? If not, it (or some version of it) probably should be shared for the sake of consistent branding.

I think @mcleo-d's insight and experience is required here.

**Comment by vmbrasseur** [comment]
For this issue, how about we fix that first link, then spin the other question (standard footers) into a separate issue into the community repo?

**Comment by mcleo-d** [comment]
@psmulovics - Please raise your standard footer module idea here - https://github.com/finos/community/issues

**Comment by mcleo-d** [comment]
Hi @psmulovics and @vmbrasseur,

I have raised https://github.com/finos/open-source-readiness/pull/32/ to resolve this issue. The site changes can be reviewed below.

https://deploy-preview-32--open-source-readiness.netlify.app/

James.
