### ISSUE TITLE
20 Mar 2024 - Open Source Readiness Meeting Agenda

### ISSUE THREAD

**Issue by robmoffat** [finos/open-source-readiness#252]
## Date
YYYYMMDD - time

## Untracked attendees
- Fullname, Affiliation, (optional) GitHub username
- ...

## Meeting notices
- FINOS **Project leads** are responsible for observing the FINOS guidelines for [running project meetings](https://community.finos.org/docs/governance/meeting-procedures/). Project maintainers can find additional resources in the [FINOS Maintainers Cheatsheet](https://community.finos.org/docs/finos-maintainers-cheatsheet).

- **All participants** in FINOS project meetings are subject to the [LF Antitrust Policy](https://www.linuxfoundation.org/antitrust-policy/), the [FINOS Community Code of Conduct](https://community.finos.org/docs/governance/code-of-conduct) and all other [FINOS policies](https://community.finos.org/docs/governance/#policies). 

- FINOS meetings involve participation by industry competitors, and it is the intention of FINOS and the Linux Foundation to conduct all of its activities in accordance with applicable antitrust and competition laws. It is therefore extremely important that attendees adhere to meeting agendas, and be aware of, and not participate in, any activities that are prohibited under applicable US state, federal or foreign antitrust and competition laws. Please contact legal@finos.org with any questions.

- FINOS project meetings may be recorded for use solely by the FINOS team for administration purposes. In very limited instances, and with explicit approval, recordings may be made more widely available.

## Agenda
- [ ] Convene & roll call (5mins)
- [ ] Display [FINOS Antitrust Policy summary slide](https://community.finos.org/Compliance-Slides/Antitrust-Compliance-Slide.pdf) 
- [ ] Review Meeting Notices (see above)
- [ ] Approve past meeting minutes
- [ ] Mimi - Annotated Policy 
- [ ] Rob - Maturity Checklist
- [ ] Rob - Using Open Source
- [ ] AOB, Q&A & Adjourn (5mins)

## Decisions Made
- [ ] Decision 1
- [ ] Decision 2
- [ ] ...

## Action Items
- [ ] Action 1
- [ ] Action 2
- [ ] ...

### Zoom Details
- https://zoom.us/j/93808780892
- Meeting ID: 938 0878 0892
- Passcode: 358724

### Join by Phone
- Find your local number: https://zoom.us/u/adl5rhui4P

**Comment by mimiflynn** [comment]
Mimi Flynn / Morgan Stanley

**Comment by psmulovics** [comment]
Peter Smulovics / Morgan Stanley

**Comment by robmoffat** [comment]
Rob Moffat / FINOS 🐈

**Comment by kmdchew** [comment]
Kristin Chew / CFG

**Comment by caradelia** [comment]
Cara Delia / Red Hat

**Comment by katnovakovic** [comment]
Katrina - Citi

**Comment by robmoffat** [comment]
### Integrating Citi Policy
- MF presented her annotated Policy document here: https://osr.finos.org/docs/bok/Artifacts/Reference-FOSS-Policy
- Opinion on the call was that this was a great piece of work.

### Maturity Checklist
- RM showed the maturity checklist, tied back to OSMM activities here: https://github.com/finos/open-source-readiness/pull/223#issuecomment-1980630978
- PS asked whether there would be a marketing push around the new checklist.  
- RM said it could either be part of OSFF, or earlier depending on how long the SIG took to review.
- PS discussed the problem with the text in the downloadable PDF being blurred, consensus that it probably wasn't worth fixing atm, but if we moved to SVG it would go away.
- Discussed that the downloadable PDF didn't really have FINOS branding on it.
- VL felt that we should try and engage firm leadership and use this to "get the OSPO in the boardroom".
- RM to ask the community to review and test the checklist out.


### Using Open Source
 - RM wrote up discussion with Madlen Wilmes about starting to use open source in a FS environment https://github.com/finos/open-source-readiness/pull/250
 - Amol suggested some extra text on use of open source within different environments: personal, startup, large corp.
 - Agreed to add this before merging.

### AOB
 - BI / PS - asking about CCC project presentation Grace Hopper Institute
 - PS asked about whether we should send a request for an information architect.  RM said he would create a video asking for one to get involved.
 - KOD joined the call to discuss ways in which different SIGs could collaborate together on funding and member benefits.  Will be producing a proper proposal on this.
