### ISSUE TITLE
17 Apr 2024 - Open Source Readiness Meeting Agenda

### ISSUE THREAD

**Issue by robmoffat** [finos/open-source-readiness#263]
## Date
20240417 - 2PM UK, 9AM EST

## Untracked attendees
- Fullname, Affiliation, (optional) GitHub username
- ...

## Meeting notices
- FINOS **Project leads** are responsible for observing the FINOS guidelines for [running project meetings](https://community.finos.org/docs/governance/meeting-procedures/). Project maintainers can find additional resources in the [FINOS Maintainers Cheatsheet](https://community.finos.org/docs/finos-maintainers-cheatsheet).

- **All participants** in FINOS project meetings are subject to the [LF Antitrust Policy](https://www.linuxfoundation.org/antitrust-policy/), the [FINOS Community Code of Conduct](https://community.finos.org/docs/governance/code-of-conduct) and all other [FINOS policies](https://community.finos.org/docs/governance/#policies). 

- FINOS meetings involve participation by industry competitors, and it is the intention of FINOS and the Linux Foundation to conduct all of its activities in accordance with applicable antitrust and competition laws. It is therefore extremely important that attendees adhere to meeting agendas, and be aware of, and not participate in, any activities that are prohibited under applicable US state, federal or foreign antitrust and competition laws. Please contact legal@finos.org with any questions.

- FINOS project meetings may be recorded for use solely by the FINOS team for administration purposes. In very limited instances, and with explicit approval, recordings may be made more widely available.

## Agenda
- [x] Convene & roll call (5mins)
- [x] Display [FINOS Antitrust Policy summary slide](https://community.finos.org/Compliance-Slides/Antitrust-Compliance-Slide.pdf) 
- [x] Review Meeting Notices (see above)
- [x] Approve past meeting minutes
- [x] [InnerSource Job Creator PR](https://github.com/finos/open-source-readiness/pull/258)
- [x] [OSRB](https://github.com/finos/open-source-readiness/pull/256)
- [x] [Merge Maturity Checklist?](https://github.com/finos/open-source-readiness/pull/223)
- [x] AOB, Q&A & Adjourn (5mins)

### Zoom Details
- https://zoom.us/j/93808780892
- Meeting ID: 938 0878 0892
- Passcode: 358724

### Join by Phone
- Find your local number: https://zoom.us/u/adl5rhui4P

**Comment by robmoffat** [comment]
Rob / FINOS 🚈

**Comment by mimiflynn** [comment]
Mimi Flynn / Morgan Stanley

**Comment by AmolMeshram19** [comment]
Amol Meshram/ LSEG

**Comment by katnovakovic** [comment]
Katrina Novakovic - Citi

**Comment by psmulovics** [comment]
Peter Smulovics / Morgan Stanley

**Comment by HelloKay27** [comment]
Kay XiongPachay / Goldman Sachs

**Comment by mimiflynn** [comment]
Search OSRB on this page: https://www.linuxfoundation.org/resources/open-source-guides/using-open-source-code

**Comment by robmoffat** [comment]
## Review of #258 

See https://github.com/finos/open-source-readiness/pull/258 comments

## InnerSource Charge Back

PS raised this as an issue.
KC - There can be ways to avoid charge back systems, such as giving developers time to work on InnerSource projects.  You volunteer and your time is then split.  
MF - discussing at own firm how this might work.
KN- often contribution to InnerSource is a maturity issue.  You need the firm to all be at the same place wrt allowing InnerSource contribution.  

## OSRB #256

See https://github.com/finos/open-source-readiness/pull/256 comments

## Maturity Checklist #223 

- AM and NJ both said they would like time to review this.  

## OSFF

- NJ said she'd been approved to speak but was travel currently unfunded.

**Comment by jessicapeng** [comment]
Jessica Peng / Goldman Sachs

**Comment by Neetuj** [comment]
@robmoffat  just slight correction to the notes .. "Neetu shared that her talk was accepted by OSFF but currently not sure if of attendance to OSFF (since travel was not funded by that time)" 

I am now trying to get the talk moved to OSFF NYC.
