### ISSUE TITLE
Bug on OSR docs site

### ISSUE THREAD

**Issue by wendallkaters** [finos/open-source-readiness#271]
https://osr.finos.org/docs/bok/activities/level-3/making-the-case is coming up with a crash error. See screenshot.
![Screenshot 2024-05-21 at 1 44 20 PM](https://github.com/finos/open-source-readiness/assets/68610775/d03eb5b1-2cf6-4c32-84f9-d3dbf2312615)

**Comment by psmulovics** [comment]
Thank you for noting - @robmoffat  fixed it and we published
