### ISSUE TITLE
05 Jun 2024 - Open Source Readiness Meeting Agenda

### ISSUE THREAD

**Issue by robmoffat** [finos/open-source-readiness#274]
## Date
20240605 -3PM UK, 10AM US

## Untracked attendees
- Fullname, Affiliation, (optional) GitHub username
- ...

## Meeting notices
- FINOS **Project leads** are responsible for observing the FINOS guidelines for [running project meetings](https://community.finos.org/docs/governance/meeting-procedures/). Project maintainers can find additional resources in the [FINOS Maintainers Cheatsheet](https://community.finos.org/docs/finos-maintainers-cheatsheet).

- **All participants** in FINOS project meetings are subject to the [LF Antitrust Policy](https://www.linuxfoundation.org/antitrust-policy/), the [FINOS Community Code of Conduct](https://community.finos.org/docs/governance/code-of-conduct) and all other [FINOS policies](https://community.finos.org/docs/governance/#policies). 

- FINOS meetings involve participation by industry competitors, and it is the intention of FINOS and the Linux Foundation to conduct all of its activities in accordance with applicable antitrust and competition laws. It is therefore extremely important that attendees adhere to meeting agendas, and be aware of, and not participate in, any activities that are prohibited under applicable US state, federal or foreign antitrust and competition laws. Please contact legal@finos.org with any questions.

- FINOS project meetings may be recorded for use solely by the FINOS team for administration purposes. In very limited instances, and with explicit approval, recordings may be made more widely available.

## Agenda
- [x] Convene & roll call (5mins)
- [x] Display [FINOS Antitrust Policy summary slide](https://community.finos.org/Compliance-Slides/Antitrust-Compliance-Slide.pdf) 
- [x] Review Meeting Notices (see above)
- [ ] Cali Dolfi, RedHat, 8Knot.
- [ ] AOB, Q&A & Adjourn (5mins)

### Zoom Details
- https://zoom.us/j/93808780892
- Meeting ID: 938 0878 0892
- Passcode: 358724

### Join by Phone
- Find your local number: https://zoom.us/u/adl5rhui4P

**Comment by BrittanyIstenes** [comment]
Brittany Istenes - FNMA

**Comment by robmoffat** [comment]
Rob Moffat / FINOS

**Comment by psmulovics** [comment]
Peter Smulovics / Morgan Stanley

**Comment by mcleo-d** [comment]
James McLeod / NatWest

**Comment by mimiflynn** [comment]
Mimi Flynn / Morgan Stanley

**Comment by JamieSlome** [comment]
Jamie Slome from @citi 🤘

**Comment by HelloKay27** [comment]
Kay XiongPachay / Goldman Sachs

**Comment by robmoffat** [comment]
Questions asked at the start of the meeting (zoom):

Amol (5 Jun 2024, 15:08)
Who is supporting project?
Is is funded?
 
You (5 Jun 2024, 15:08)
Should we expect an open source community to form around an open source project?
 
Amol (5 Jun 2024, 15:09)
License policy?
 
You (5 Jun 2024, 15:09)
How do I make sure quieter voices in the community are heard?
From a financial services perspective, how can I get my staff engaged in a community without reputational risks?
Nuredin Omer joined as a guest
 
Amol (5 Jun 2024, 15:10)
Security issues
Community engagement
 
Peter Smulovics (5 Jun 2024, 15:10)
How viable it is? Are there possible inference of state actors? How many active maintainers? 
 
Amol (5 Jun 2024, 15:10)
Supportability
 
You (5 Jun 2024, 15:10)
As an OSPO, how can I encourage community and growth in strategic open source projects that my firm depends on?
 
Amol (5 Jun 2024, 15:11)
Who is maintaining?

**Comment by robmoffat** [comment]
https://eightknot.osci.io

**Comment by katnovakovic** [comment]
Katrina Novakovic - Citi

**Comment by robmoffat** [comment]
More links from the talk:

https://chaoss.community/kb-metrics-and-metrics-models/
https://github.com/oss-review-toolkit/ort
https://backstage.io/
https://github.com/backstage/backstage
