### ISSUE TITLE
18 Sept 2024 - Open Source Readiness Meeting Agenda

### ISSUE THREAD

**Issue by robmoffat** [finos/open-source-readiness#295]
## Date
20240918 - 9AM EST, 2PM BST.

## Untracked attendees
- Fullname, Affiliation, (optional) GitHub username
- ...

## Meeting notices
- FINOS **Project leads** are responsible for observing the FINOS guidelines for [running project meetings](https://community.finos.org/docs/governance/meeting-procedures/). Project maintainers can find additional resources in the [FINOS Maintainers Cheatsheet](https://community.finos.org/docs/finos-maintainers-cheatsheet).

- **All participants** in FINOS project meetings are subject to the [LF Antitrust Policy](https://www.linuxfoundation.org/antitrust-policy/), the [FINOS Community Code of Conduct](https://community.finos.org/docs/governance/code-of-conduct) and all other [FINOS policies](https://community.finos.org/docs/governance/#policies). 

- FINOS meetings involve participation by industry competitors, and it is the intention of FINOS and the Linux Foundation to conduct all of its activities in accordance with applicable antitrust and competition laws. It is therefore extremely important that attendees adhere to meeting agendas, and be aware of, and not participate in, any activities that are prohibited under applicable US state, federal or foreign antitrust and competition laws. Please contact legal@finos.org with any questions.

- FINOS project meetings may be recorded for use solely by the FINOS team for administration purposes. In very limited instances, and with explicit approval, recordings may be made more widely available.

## Agenda
- [ ] Convene & roll call (5mins)
- [ ] Display [FINOS Antitrust Policy summary slide](https://community.finos.org/Compliance-Slides/Antitrust-Compliance-Slide.pdf) 
- [ ] Review Meeting Notices (see above)
- [ ] Approve past meeting minutes
- [ ] Agenda for OSR Round Table
- [ ] 4th OSR CO-Chair Seat
- [ ] Foundations beginner's guide
- [ ] AOB, Q&A & Adjourn (5mins)

## Decisions Made
- [ ] Decision 1
- [ ] Decision 2
- [ ] ...

## Action Items
- [ ] Action 1
- [ ] Action 2
- [ ] ...

### Zoom Details
- https://zoom.us/j/93808780892
- Meeting ID: 938 0878 0892
- Passcode: 358724

### Join by Phone
- Find your local number: https://zoom.us/u/adl5rhui4P

**Comment by caradelia** [comment]
Cara Delia / Red Hat

**Comment by robmoffat** [comment]
Rob Moffat / FNOS 🦑

**Comment by HelloKay27** [comment]
Kay XiongPachay / Goldman Sachs

**Comment by BrittanyIstenes** [comment]
Brittany Istenes - FNMA

**Comment by pcheong-lbg** [comment]
Pooi Cheong - Lloyds

**Comment by psmulovics** [comment]
Peter Smulovics / Morgan Stanley

**Comment by robmoffat** [comment]
Minutes

1. OSR Roundtable

- Cost of Forks
- Maturity Survey Results
- InnerSource Adoption / Metrics

2. 4th Co-Chair
- Kay nominated
- RM to send email asking for further nominations

3. Foundations Article

- FINOS are doing a beginner guide
- Microsoft a good example, using KPIs.  
- What other tips are there?
- Peter (in his ambassador role) and Rimma working on a starter pack looking at certain projects
- Could we get budget for graphics visual, kinaesthetic and auditory - visual guide for navigating your foundation.
- The landscape doesn't show connections.  How are the projects connected? How are the foundations connected?
- We need a white boarding session.
- Could we get Kevlin to help with this at OSFF?   - Make a shortlist of new developers to talk to, new FINOS joiners.
- Ask for feedback on the experience of joining.
- "How To Maximise the Benefits of Membership"

4.l. Next OSR Meeting
- Cancel on Oct 2nd, as we're all in transit.
- 6th Nov: https://github.com/oss-review-toolkit/ort  ?

**Comment by robmoffat** [comment]
@tsteenbe  - are you still good for this on the 6th? ☝️
