### ISSUE TITLE
04 Aug 2021 - Open Source Readiness Meeting Agenda & Minutes

### ISSUE THREAD

**Issue by copiesofcopies** [finos/open-source-readiness#3]
## Date
2021-08-04 - 10:00 am EDT

## WebEx info
- Webex: https://finos.webex.com/finos/j.php?MTID=mec6bb47084d671bc772c0652add2605c
- Meeting number: 664 434 054

### Join by phone
- +1-415-655-0003 US Toll
- +44-20319-88141 UK Toll
- Access code: 664 434 054

## Agenda
- [ ] Convene & roll call (5 min)
- [ ] Display [FINOS Antitrust Policy summary slide](https://github.com/finos/community/blob/master/governance/Compliance-Slides/Antitrust-Compliance-Slide.pdf) and review notices (see below)
- [ ] Andrew Aitken (Wipro): presentation of a high-level roadmap for the OSR SIG, and a proposed framework for an open source maturity model to be collaboratively developed by the SIG./
- [ ] AOB, Q&A & Adjourn (5 min)

## Meeting notices
- FINOS **Project leads** are responsible for observing the FINOS guidelines for [running project meetings](https://github.com/finos/community/blob/master/governance/Meeting-Procedures.md#run-the-meeting). Project maintainers can find additional resources in the [FINOS Maintainers Cheatsheet](https://odp.finos.org/docs/finos-maintainers-cheatsheet/).

- **All participants** in FINOS project meetings are subject to the [LF Antitrust Policy](https://www.linuxfoundation.org/antitrust-policy/), the [FINOS Community Code of Conduct](https://github.com/finos/community/blob/master/governance/Code-of-Conduct.md) and all other [FINOS policies](https://github.com/finos/community/tree/master/governance#policies). 

- FINOS meetings involve participation by industry competitors, and it is the intention of FINOS and the Linux Foundation to conduct all of its activities in accordance with applicable antitrust and competition laws. It is therefore extremely important that attendees adhere to meeting agendas, and be aware of, and not participate in, any activities that are prohibited under applicable US state, federal or foreign antitrust and competition laws. Please contact legal@finos.org with any questions.

- FINOS project meetings may be recorded for use solely by the FINOS team for administration purposes. In very limited instances, and with explicit approval, recordings may be made more widely available.

## Untracked attendees
- Andrew Aitken, Wipro
- Aaron Williamson, FINOS
- James McLeod, FINOS
- Alexandra Stratigos, FINOS
- Ankit Pandey, Wipro
- Brian Ingenito, Morgan Stanley
- Clare Dillon, InnerSource Commons
- Aitana Myohl, FINOS
- Gabriele Columbro, FINOS
- Gil Yehuda, US Bank
- Girish Ahuja, SMBC
- Gurukiran Krishnamurthy, Wipro
- Jane Gavronsky, FINOS
- Jason Beres, Infragistics
- Matthew Dietz, BNY Mellon
- Padmalav Sahoo, Wipro
- Paul Childrehose, Canadian RegTech Association
- Sally Ellard, Deutsche Bank
- Sundeep Dadlani, RBC
- VM Brasseur, Wipro
- Yury Nino
- Rob Winchester

## Decisions Made
- [ ] Decision 1
- [ ] Decision 2
- [ ] ...

## Action Items
- [ ] Action 1
- [ ] Action 2
- [ ] ...

**Comment by mcleo-d** [comment]
The [FINOS InnerSource SIG](https://github.com/finos/InnerSource) is creating an [InnerSource Maturity Model](https://github.com/finos/InnerSource/discussions/12) and would like to create an Infographic that represents the relationship between InnerSource vs Open Source (pros/cons/differences) cc @godds

@claredillon will join OSR to represent the InnerSource SIG as OSR moves forward with the OSR Open Source Maturity Model (https://github.com/finos/InnerSource/issues/26).

InnerSource GitHub Discussion -> https://github.com/finos/InnerSource/discussions/13#discussioncomment-898550 
![Screenshot 2021-08-02 at 17 08 32](https://user-images.githubusercontent.com/6029572/127899239-957fed6d-b10a-4666-9e31-e9ec47778a18.png)

**Comment by Julia-Ritter** [comment]
Julia // FINOS

**Comment by vmbrasseur** [comment]
I just noticed that this issue contains no notes from the call. Retroactively adding some here:

## 2021-08-04

* First meeting of the group as a SIG
    * Was a project before
    * OSR dates back to the Symphony days (pre-FINOS)
    * Few fintech companies had started FOSS practice stuff back then
        * Needed experienced advice
    * Lots of progress since then
        * More institutional knowledge among the members now
    * Changed to a SIG to get more participation from members
        * Want to draw out that institutional knowledge
* Collaboration with Wipro
    * Co-chair this SIG along w/friends at RBC (Sandeep Dadlani (SD))
* First project of SIG: Open Source Maturity Model (OSMM)
    * Contributing an instantiation of the OSMM
    * v3.0, but lots of room for contribution
* But first…roll call
* Background on the OSMM
    * Intent
        * Where they are, where they'd like to be, how to get there
    * FINOS has existing OSR assessment & maturity framework
        * Will incorporate and evolve
    * Will be self-service
        * Survey -> output
            * placement on OSMM
            * spider chart
            * interview summaries
    * Current state analysis, then future state planning
    * Implement then refine
* Explanation of the model
    * Dimentions -> Elements -> Maturity stage
* Attendee 1: A single org may have different opinions about goals
    * How does the model help with that?
    * Helps orgs know where they are; not judging
        * Up to them to determine which stage is right for them
* Good to see Innersource in OSMM; that SIG working on own maturity model
    * Integrate?
    * Innersource SIG: YES, PLEASE
    * Absolutely; failure if we don't do this
* OSMM implementation plan
    * Present today
    * Move docs to FINOS GH by Aug 26th
        * Glossary
        * Explanation of output
        * Model internals
    * Release next version before next SIG meeting (Sept 01)
    * Go live target: Sept 09
        * Depends on feedback, release of FINOS new website
* Participating
    * Want input on the model itself
        * Design, workflow, process
    * Step up to take ownership of a dimension or element
        * For instance, Innersource SIG take ownership of that element
    * Help with docs
    * Looking for folks here to create content (blog post, white paper, etc)
    * Will need some collateral & PR
* What license for OSMM?
    * In active talks about that, but something CC, probably SA
    * CC-SA being socialised inside; expect no push back
* Attendee 2: Starting this journey internally
    * For this, guided website to help people get to where they want to go
        * Template policies for certain stages
    * Interesting question
        * Would be a highly advanced evolution
        * But have found the policies aren't important to the journey
    * v1.0 OSS policies typically are reactive in nature & restrictive
        * We recommend doing strategy first: what do you want to do with FOSS?
        * This will inform the policy
        * Don't do a policy in a vacuum w/o the processes
        * Strategy + policy + process needed for something truly descriptive
* How to contribute to OSMM?
    * Different formats for different elements of the model
    * Implementation based on FINOS IT
    * Wipro will deliver implementable model & the survey
    * Format for these will require more conversations w/the FINOS team
* Email aaron@finos.org to be added to the FINOS OSR list
    * Or email to osr+subscribe finos.org
* Slack channel as well

**Comment by gravax** [comment]
I am good with these notes.
