### ISSUE TITLE
Document guidance for records management identity wrt OSS

### ISSUE THREAD

**Issue by vmbrasseur** [finos/open-source-readiness#35]
### Description of Problem:

In #26 "how do banks deal with records management identity wrt OSS" came up as a common problem.

### Potential Solutions:

We should provide a new resource page for this topic on the [OSR microsite](https://osr.finos.org).

**Comment by vmbrasseur** [comment]
We need more information for this one. 

1. What sort of records? 
2. How are they required to be managed? 
3. Identity…of what? 
4. What are the use cases we should consider when drafting this resource page?

**Comment by vmbrasseur** [comment]
From conversation during the #31 call…

* Related to retention policy mentioned in #34
* What kind of records are these?
    * All email communication is archived for X yrs
    * All internal source code archived for X yrs
    * All internal chat systems (Symphony, etc)
    * Also anything involving counter-parties
    * This all applies to ALL firm business
    * Some of the records and communications are surveiled in real time
        * So would need an exception for surveilance for open source-related communication
* How are they required to be managed
    * Retention for X years, real time surveilance
    * Will be fed/gov regulations around this
* Identity…of what?
    * What does identity mean in that sense?
    * Identify who did what
    * For instance, anyone can create a random GH account, or contributions can come in from an employee's account but it's not associated with their work email address
    * Start here on our next call (if we don't get an answer before then)

**Comment by psmulovics** [comment]
- All kinds of records - whether it is email, IM (symphony, bloomberg chat, etc), etc needs to be surveyed and stored if it is firm business
- Importance of marking OSS not a firm business
- Abundance of other communication methods that are not monitored
- Is there a federal / regulatory / government level document to link to?
- Likely there are firm wide communication policies, and an OSS policy that carves out the exceptions
- What does identity mean? Is it "Contribution attribution to the actual identity"?

**Comment by psmulovics** [comment]
Based on discussions, I can confirm such document is not needed due to the fact that the OSS work is not considered 'firm business' therefore none of the policies otherwise applying to communication would apply.
