### ISSUE TITLE
Document guidance about access to OSS projects for financial services 

### ISSUE THREAD

**Issue by vmbrasseur** [finos/open-source-readiness#36]
### Description of Problem:

In #26 "access to OSS projects (when are maintainers vs. when contributors)" came up as a common challenge faced by financial services institutions.

### Potential Solutions:

Add a new resource page to the [OSR microsite](https://osr.finos.org) to provide some guidance on this topic.

**Comment by vmbrasseur** [comment]
We need more information for this one.

1. What are the use cases we should consider when drafting the resource page?
2. What type of access does this topic refer to, and access by/for whom?

**Comment by troups** [comment]
we should check whether the code repo and SDLC is NOT covered by default, but some aspects of engineering in a regulated role (say algo development) could fall into a function that has a more rigorous requirement that changes that default

**Comment by mcleo-d** [comment]
cc @pholleran and @robmoffat for GitHub involvement and a quick conversation at Open Source in Finance Forum, London on July 13th.

**Comment by vmbrasseur** [comment]
Feedback from #45:

* Many people who work in banks can't access GitHub
    * Protect confidential information (DLP: Data Leakage Protection)
    * Sometimes will be accessible in a read-only (GET not POST)
* Usually need to apply for an exception to access
* What sort of information is helpful to include in that exception application?
    * List of projects you're working on
    * Benefits of risk minimisation by contributing upstream (as compared to internal fork)
* Workarounds
    * Mirror FOSS projects internally (can see the project but not contribute back)
        * Dangers of internal forks
    * git-proxy FINOS project
        * Commit internally, push out publicly
    * Use personal laptop for contributions
        * But this leaks IP
        * Could violate employment agreement
        * Still need approval to do this
    * Use personal GH account
        * Set up multiple emails
        * Use work email for work contributions
* Would love GitHub/Gitlab to work with them
    * What are the URLs that need to be proxied just so they can _see_ the sites (but not contribute)?
    * What are the URLs that IT can proxy/approve viewing (w/o logging in)
    * VMB will contact Ashley & James will talk to Phil (both at GitHub) about getting this added
