### ISSUE TITLE
01 June 2022 - Open Source Readiness Meeting Agenda

### ISSUE THREAD

**Issue by mcleo-d** [finos/open-source-readiness#39]
## Date
01 June 2022 - 3pm UK / 10am ET

## Untracked attendees
- Fullname, Affiliation, (optional) GitHub username
- ...

## Meeting notices
- FINOS **Project leads** are responsible for observing the FINOS guidelines for [running project meetings](https://github.com/finos/community/blob/master/governance/Meeting-Procedures.md#run-the-meeting). Project maintainers can find additional resources in the [FINOS Maintainers Cheatsheet](https://odp.finos.org/docs/finos-maintainers-cheatsheet/).

- **All participants** in FINOS project meetings are subject to the [LF Antitrust Policy](https://www.linuxfoundation.org/antitrust-policy/), the [FINOS Community Code of Conduct](https://github.com/finos/community/blob/master/governance/Code-of-Conduct.md) and all other [FINOS policies](https://github.com/finos/community/tree/master/governance#policies). 

- FINOS meetings involve participation by industry competitors, and it is the intention of FINOS and the Linux Foundation to conduct all of its activities in accordance with applicable antitrust and competition laws. It is therefore extremely important that attendees adhere to meeting agendas, and be aware of, and not participate in, any activities that are prohibited under applicable US state, federal or foreign antitrust and competition laws. Please contact legal@finos.org with any questions.

- FINOS project meetings may be recorded for use solely by the FINOS team for administration purposes. In very limited instances, and with explicit approval, recordings may be made more widely available.

## Agenda
- [x] Convene & roll call (5mins)
- [x] Display [FINOS Antitrust Policy summary slide](https://github.com/finos/community/blob/master/governance/Compliance-Slides/Antitrust-Compliance-Slide.pdf) 
- [x] Review Meeting Notices (see above)
- [x] Approve past meeting minutes: #31 
- [x] [Open Source in Finance Hybrid NYC Meetup](https://zoom.us/webinar/register/2416540182543/WN_TcmWGDmDSJ2kpy57gw0N5A) on June 8th 2022
- [x] [Open Source in Finance Forum](https://events.linuxfoundation.org/open-source-finance-forum-london/) in London on July 13th 2022
- [x] Pull Request Reviews 
  - https://github.com/finos/open-source-readiness/pull/41 - @vmbrasseur 
  - https://github.com/finos/open-source-readiness/pull/42 - @mcleo-d 
- [x] OSR Kanban Review - https://github.com/orgs/finos/projects/28 - @mcleo-d 
- [x] AOB, Q&A & Adjourn (5mins)

## Minutes
- Open Source in Finance Forum registration to OSR community
- PR https://github.com/finos/open-source-readiness/pull/41 reviewed and merged
- PR request https://github.com/finos/open-source-readiness/pull/42 reviewed
  -  Agreed by community a comment should be made when commits merged without review
- OSR Kanban Reviewed 
  - https://github.com/orgs/finos/projects/28
- Discussion on whether #35 is needed in banks
- #12 to `in progress` to be determined outside OSR call
- Discussion on #36 
  - SDLC comment - https://github.com/finos/open-source-readiness/issues/36#issuecomment-1143712076

## Open Source in Finance Hybrid NYC Meetup, June 8th 2022

June 8th 2022 - Join us for our New York City / hybrid [Open Source in Finance Meetup](https://zoom.us/webinar/register/2416540182543/WN_TcmWGDmDSJ2kpy57gw0N5A) at the Synechron offices in Times Square. Networking will start from 5.30pm, and talks at 6.30pm.

Presentations include ...

- **Stephen Goldbaum**, Executive Director at Morgan Stanley and Lead Maintainer of the FINOS Morphir project
- **Sandeep Kumar**, FinLabs at Synechron. Horizon Scanning of Compliance Regulations (FINRA, ESMA, …)
- **Paul Childerhose**, Member of the Board of Directors at Canadian RegTech Association and Canadian Regional Advocate for the EDM Council.

If you're not able to join us in person, don't worry! **Register below and join us online at 6.30pm**.

👉🏻 [Register to join the NYC meetup here](https://zoom.us/webinar/register/2416540182543/WN_TcmWGDmDSJ2kpy57gw0N5A)

<a href="https://zoom.us/webinar/register/2416540182543/WN_TcmWGDmDSJ2kpy57gw0N5A"><img src="https://user-images.githubusercontent.com/6029572/171235502-c81a890c-ec12-4118-8088-64a1694d0cfd.png" width="85%" /></a>

## Open Source in Finance Forum London, July 13th 2022

Register below for the FINOS [Open Source in Finance Forum](https://events.linuxfoundation.org/open-source-finance-forum-london/) in London on July 13th 2022 👾💥

Open Source in Finance Forum is the only conference dedicated to driving collaboration and innovation in financial services through open source software and standards.

We bring together experts across financial services, technology, and open source to engage our community in stimulating and thought-provoking conversations about how to best (and safely) leverage open source software to solve industry challenges.

FINOS members employees are eligible to receive complimentary registration as part of their company’s membership. Please email [osff@finos.org](mailto:osff@finos.org) to request the Finos Member access code.

Register and find out more 👉🏻 https://events.linuxfoundation.org/open-source-finance-forum-london/

<a href="https://events.linuxfoundation.org/open-source-finance-forum-london/"><img src="https://user-images.githubusercontent.com/6029572/171230930-a68f99a3-ac8d-4738-8054-87af2d45b544.png" width="85%" /></a>

### WebEx info
- Webex: https://finos.webex.com/finos/j.php?MTID=mec6bb47084d671bc772c0652add2605c
- Meeting number: 664 434 054

### Join by phone
- +1-415-655-0003 US Toll
- +44-20319-88141 UK Toll
- Access code: 664 434 054

**Comment by psmulovics** [comment]
🙋‍♂️

**Comment by matthyx** [comment]
hi folks!

**Comment by pholleran** [comment]
![hi-hello](https://user-images.githubusercontent.com/4007128/171423276-79cc19c3-4ead-4dcb-84db-aa4759da8c55.gif)

**Comment by jgavronsky** [comment]
Jane / FINOS

**Comment by troups** [comment]
simon / soton business school

**Comment by mcleo-d** [comment]
@psmulovics and @vmbrasseur - I have added the minutes to this agenda  🌴 🦕 🌤️

**Comment by vmbrasseur** [comment]
Emailed asking for comments on the minutes. Received none, so I'm approving them and closing the issue.
