### ISSUE TITLE
01 Sep 2021 - Open Source Readiness Meeting Agenda & Minutes

### ISSUE THREAD

**Issue by mcleo-d** [finos/open-source-readiness#4]
## Date
2021-08-04 - 10:00 am EDT

## WebEx info
- Webex: https://finos.webex.com/finos/j.php?MTID=mec6bb47084d671bc772c0652add2605c
- Meeting number: 664 434 054

### Join by phone
- +1-415-655-0003 US Toll
- +44-20319-88141 UK Toll
- Access code: 664 434 054

## Agenda
- Agenda review and participant additions
- SIG communication model discussion - email, Slack, GitHub, Confluence, etc.,
- Open Source Maturity Model (OSMM) update 
  - GitHub repo structure
  - documentation
  - model update
- SIG future topics?
- Other business

## Meeting notices
- FINOS **Project leads** are responsible for observing the FINOS guidelines for [running project meetings](https://github.com/finos/community/blob/master/governance/Meeting-Procedures.md#run-the-meeting). Project maintainers can find additional resources in the [FINOS Maintainers Cheatsheet](https://odp.finos.org/docs/finos-maintainers-cheatsheet/).

- **All participants** in FINOS project meetings are subject to the [LF Antitrust Policy](https://www.linuxfoundation.org/antitrust-policy/), the [FINOS Community Code of Conduct](https://github.com/finos/community/blob/master/governance/Code-of-Conduct.md) and all other [FINOS policies](https://github.com/finos/community/tree/master/governance#policies). 

- FINOS meetings involve participation by industry competitors, and it is the intention of FINOS and the Linux Foundation to conduct all of its activities in accordance with applicable antitrust and competition laws. It is therefore extremely important that attendees adhere to meeting agendas, and be aware of, and not participate in, any activities that are prohibited under applicable US state, federal or foreign antitrust and competition laws. Please contact legal@finos.org with any questions.

- FINOS project meetings may be recorded for use solely by the FINOS team for administration purposes. In very limited instances, and with explicit approval, recordings may be made more widely available.

## Untracked attendees
- Fullname, Affiliation, (optional) GitHub username
- ...

## Decisions Made
- [ ] Decision 1
- [ ] Decision 2
- [ ] ...

## Action Items
- [ ] Action 1
- [ ] Action 2
- [ ] ...

**Comment by mvdietz** [comment]
Matthew Dietz from BNY Mellon

**Comment by gyehuda** [comment]
Attended. 
Head of Open Source at U..S Bank

**Comment by vmbrasseur** [comment]
Howdy. Wipro affiliation.

**Comment by gravax** [comment]
Hi!

Gilles Gravier, Wipro, @gravax

**Comment by jgavronsky** [comment]
Jan Gavronsky @ FINOS here

**Comment by mcleo-d** [comment]
James McLeod - FINOS Director of Community 

Hello ... 😁

**Comment by copiesofcopies** [comment]
Aaron Williamson @ FINOS

**Comment by Julia-Ritter** [comment]
Untracked attendees:
 - Padmalav Sahoo / Wipro 
 - Ankit Pandey / Wipro
 - Ken Dauria / The Hartford 
 - Alex Nasjletti / jri-america
 - Girish Ahuja / jri-america.com
 - Andrew aitken / Wipro
 - Anthony Vacca / RBC 
- FINOS Projects / Julia

**Comment by gravax** [comment]
All good for me.
