### ISSUE TITLE
06 July 2022 - Open Source Readiness Meeting Agenda

### ISSUE THREAD

**Issue by mcleo-d** [finos/open-source-readiness#45]
## Date
06 July 2022 - 3pm UK / 10am ET

## Untracked attendees
- Fullname, Affiliation, (optional) GitHub username
- ...

## Meeting notices
- FINOS **Project leads** are responsible for observing the FINOS guidelines for [running project meetings](https://github.com/finos/community/blob/master/governance/Meeting-Procedures.md#run-the-meeting). Project maintainers can find additional resources in the [FINOS Maintainers Cheatsheet](https://odp.finos.org/docs/finos-maintainers-cheatsheet/).

- **All participants** in FINOS project meetings are subject to the [LF Antitrust Policy](https://www.linuxfoundation.org/antitrust-policy/), the [FINOS Community Code of Conduct](https://github.com/finos/community/blob/master/governance/Code-of-Conduct.md) and all other [FINOS policies](https://github.com/finos/community/tree/master/governance#policies). 

- FINOS meetings involve participation by industry competitors, and it is the intention of FINOS and the Linux Foundation to conduct all of its activities in accordance with applicable antitrust and competition laws. It is therefore extremely important that attendees adhere to meeting agendas, and be aware of, and not participate in, any activities that are prohibited under applicable US state, federal or foreign antitrust and competition laws. Please contact legal@finos.org with any questions.

- FINOS project meetings may be recorded for use solely by the FINOS team for administration purposes. In very limited instances, and with explicit approval, recordings may be made more widely available.

## Agenda
- [x] Convene & roll call (5mins)
- [x] Display [FINOS Antitrust Policy summary slide](https://github.com/finos/community/blob/master/governance/Compliance-Slides/Antitrust-Compliance-Slide.pdf) 
- [x] Review Meeting Notices (see above)
- [x] Approve past meeting minutes
- [x] [Open Source in Finance Forum](https://events.linuxfoundation.org/open-source-finance-forum-london/) in London on July 13th 2022
- [x] Review doc from #35 
- [x] Gather information for completing #36 
- [x] What other documents would you like to see?
- [x] FINOS Banks OSPO Roundtable : Open Source in Finance Forum, London, July 13th 2022 at 1.40pm BST
- [x] AOB, Q&A & Adjourn (5mins)

## Open Source in Finance Forum London, July 13th 2022

Register below for the FINOS [Open Source in Finance Forum](https://events.linuxfoundation.org/open-source-finance-forum-london/) in London on July 13th 2022 👾💥

Open Source in Finance Forum is the only conference dedicated to driving collaboration and innovation in financial services through open source software and standards.

We bring together experts across financial services, technology, and open source to engage our community in stimulating and thought-provoking conversations about how to best (and safely) leverage open source software to solve industry challenges.

FINOS members employees are eligible to receive complimentary registration as part of their company’s membership. Please email [osff@finos.org](mailto:osff@finos.org) to request the Finos Member access code.

Register and find out more 👉🏻 https://events.linuxfoundation.org/open-source-finance-forum-london/

<a href="https://events.linuxfoundation.org/open-source-finance-forum-london/"><img src="https://user-images.githubusercontent.com/6029572/171230930-a68f99a3-ac8d-4738-8054-87af2d45b544.png" width="85%" /></a>

### WebEx info
- Webex: https://finos.webex.com/finos/j.php?MTID=mec6bb47084d671bc772c0652add2605c
- Meeting number: 664 434 054

### Join by phone
- +1-415-655-0003 US Toll
- +44-20319-88141 UK Toll
- Access code: 664 434 054

**Comment by gravax** [comment]
Hello!

**Comment by bingenito** [comment]
Brian Ingenito / Morgan Stanley

**Comment by cdeliaRH** [comment]
Cara Delia/Red Hat

**Comment by mcleo-d** [comment]
## Minutes 
- Add OSFF to future agendas for OSR talks etc ... 
  - https://events.linuxfoundation.org/open-source-finance-forum-new-york/

**Comment by vmbrasseur** [comment]
Emailed asking for comments on the minutes. Received none, so I'm approving them and closing the issue.
