### ISSUE TITLE
Moving the osr.finos.org website to use docosaurus v2

### ISSUE THREAD

**Issue by psmulovics** [finos/open-source-readiness#46]
For both a broader set of features and due to v1 soon EOL, we plan to bump up the site to use v2

### Acceptance criteria

- Website is running on v2
- Netlify scripts are updated
- URLs are kept working

**Comment by psmulovics** [comment]
![image](https://user-images.githubusercontent.com/28162552/173909914-2f518a57-c005-4fb8-9447-2dc70c01e93d.png)
So the general content works - footer, sidebar, theming is to be fixed.

**Comment by psmulovics** [comment]
![image](https://user-images.githubusercontent.com/28162552/173917320-84318eff-c553-41d5-af61-fa0c7450d303.png)
Footer updated save for CSS for the buttons

**Comment by psmulovics** [comment]
@robmoffat FYI

**Comment by robmoffat** [comment]
Just found it!

**Comment by robmoffat** [comment]
OK - so I did this work yesterday, it's in this draft PR: https://github.com/finos/open-source-readiness/pull/89

This also include BoK skeleton pages, so we might want to break it down to just be the Docusaurus upgrade?  WDYT?

Also at the moment the preview is breaking so I need to ask help@finos.org about getting that working

**Comment by psmulovics** [comment]
Yeah, probably we can split into two and do just the docosaurus update. If this result in changing URLs, we have to ask FINOS to update URLs on the main finos site too as that does deep link to a few osr pages.

**Comment by psmulovics** [comment]
It is likely breaking due to the needed change in the netlify scripting, which originally was something @mcleo-d offered to flip when the actual site is coming close to become v2

**Comment by robmoffat** [comment]
FINOS Infra fixed the netlify preview:  https://deploy-preview-89--open-source-readiness.netlify.app/docs/about

I don't think there will be any URL changes - this should be a straight upgrade.

PR here: 

 - https://github.com/finos/open-source-readiness/pull/93
