### ISSUE TITLE
07 September 2022 - Open Source Readiness Meeting Agenda

### ISSUE THREAD

**Issue by vmbrasseur** [finos/open-source-readiness#49]
## Date
20220907 - 3pm UK / 10am ET

## Untracked attendees
- Fullname, Affiliation, (optional) GitHub username
- ...

## Meeting notices
- FINOS **Project leads** are responsible for observing the FINOS guidelines for [running project meetings](https://github.com/finos/community/blob/master/governance/Meeting-Procedures.md#run-the-meeting). Project maintainers can find additional resources in the [FINOS Maintainers Cheatsheet](https://odp.finos.org/docs/finos-maintainers-cheatsheet/).

- **All participants** in FINOS project meetings are subject to the [LF Antitrust Policy](https://www.linuxfoundation.org/antitrust-policy/), the [FINOS Community Code of Conduct](https://github.com/finos/community/blob/master/governance/Code-of-Conduct.md) and all other [FINOS policies](https://github.com/finos/community/tree/master/governance#policies). 

- FINOS meetings involve participation by industry competitors, and it is the intention of FINOS and the Linux Foundation to conduct all of its activities in accordance with applicable antitrust and competition laws. It is therefore extremely important that attendees adhere to meeting agendas, and be aware of, and not participate in, any activities that are prohibited under applicable US state, federal or foreign antitrust and competition laws. Please contact legal@finos.org with any questions.

- FINOS project meetings may be recorded for use solely by the FINOS team for administration purposes. In very limited instances, and with explicit approval, recordings may be made more widely available.

## Agenda
- [x] Convene & roll call (5mins)
- [x] Display [FINOS Antitrust Policy summary slide](https://github.com/finos/community/blob/master/governance/Compliance-Slides/Antitrust-Compliance-Slide.pdf) 
- [x] Review Meeting Notices (see above)
- [ ] Approve past meeting minutes
- [x] @anajsana from [TODO Group](https://github.com/todogroup) presenting on TODO/FINOS OSR synergies (25 mins)
- [x] Andrew Aitken from Wipro presents the [Open Source Maturity Model](https://github.com/finos-labs/osmm) and testing next steps for the OSR SIG (25 mins)
- [x] AOB, Q&A & Adjourn (10 mins)

### WebEx info
- Webex: https://finos.webex.com/finos/j.php?MTID=mec6bb47084d671bc772c0652add2605c
- Meeting number: 664 434 054

### Join by phone
- +1-415-655-0003 US Toll
- +44-20319-88141 UK Toll
- Access code: 664 434 054

**Comment by robmoffat** [comment]
Spoke to @maoo who said the OSMM is now deployed.

**Comment by mcleo-d** [comment]
Hello 👋🏻

**Comment by vmbrasseur** [comment]
Howdy! 🤠

**Comment by mark-hoare-db** [comment]
Hi

**Comment by pholleran** [comment]
![image](https://user-images.githubusercontent.com/4007128/188898450-ee7e26ea-2b0e-4c7a-8892-0368a743dbe0.png)

**Comment by AvijitBiswas-socgen** [comment]
Hello Avi here from SocGen :)

**Comment by robmoffat** [comment]
Rob / FINOS
