### ISSUE TITLE
19 OCT 2021 - Open Source Readiness Meeting Agenda & Minutes

### ISSUE THREAD

**Issue by Julia-Ritter** [finos/open-source-readiness#5]
## Date
19 OCT 2021  - 10am ET / 3pm BST

## Untracked attendees
- Fullname, Affiliation, (optional) GitHub username
- ...

## Meeting notices
- FINOS **Project leads** are responsible for observing the FINOS guidelines for [running project meetings](https://github.com/finos/community/blob/master/governance/Meeting-Procedures.md#run-the-meeting). Project maintainers can find additional resources in the [FINOS Maintainers Cheatsheet](https://odp.finos.org/docs/finos-maintainers-cheatsheet/).

- **All participants** in FINOS project meetings are subject to the [LF Antitrust Policy](https://www.linuxfoundation.org/antitrust-policy/), the [FINOS Community Code of Conduct](https://github.com/finos/community/blob/master/governance/Code-of-Conduct.md) and all other [FINOS policies](https://github.com/finos/community/tree/master/governance#policies). 

- FINOS meetings involve participation by industry competitors, and it is the intention of FINOS and the Linux Foundation to conduct all of its activities in accordance with applicable antitrust and competition laws. It is therefore extremely important that attendees adhere to meeting agendas, and be aware of, and not participate in, any activities that are prohibited under applicable US state, federal or foreign antitrust and competition laws. Please contact legal@finos.org with any questions.

- FINOS project meetings may be recorded for use solely by the FINOS team for administration purposes. In very limited instances, and with explicit approval, recordings may be made more widely available.

## Agenda
- [ ] Convene & roll call (5mins)
- [ ] Display [FINOS Antitrust Policy summary slide](https://github.com/finos/community/blob/master/governance/Compliance-Slides/Antitrust-Compliance-Slide.pdf) 
- [ ] Review Meeting Notices (see above)
- [ ] Discussion: Check-in on current priorities
- [ ] Review of contribution statistics from State of Open Source in Financial Services
- [ ] Discussion: Contribution plans and priorities
- [ ] AOB, Q&A & Adjourn (5mins)

## Decisions Made
- [ ] Decision 1
- [ ] Decision 2
- [ ] ...

## Action Items
- [ ] Action 1
- [ ] Action 2
- [ ] ...

### WebEx info
- Webex: https://finos.webex.com/finos/j.php?MTID=mec6bb47084d671bc772c0652add2605c
- Meeting number: 664 434 054

### Join by phone
- +1-415-655-0003 US Toll
- +44-20319-88141 UK Toll
- Access code: 664 434 054

**Comment by gravax** [comment]
Agenda item could be an update on the Open Source Strategy Forum. My flight is right during the call...

**Comment by vmbrasseur** [comment]
Greetings!

**Comment by vmbrasseur** [comment]
I just noticed that this issue contains no notes from the call. Retroactively adding some here:

## 2021-10-19

Attending: Aaron Williamson, David Holland (UBS), Julia from LF, James McCleod, Gil Yehuda, Edson Kazuto Tagusagawa (Mitawoo (sp?)), Jane Gavronsky, Girish Ahuja, Andrew Aitken

* Antitrust statement
* Call is under CHR
* December 2: Panel discussion
	* IP Considerations in Open Source Contribution
	* Meeker, VanL, McCoy
	* "Bring your lawyer to OSR day!"
* Check-in questions
	* Introduce yourself
	* What is a major focus of your OS program right now?
	* What is an obstacle your OS program is currently facing?
	* What are you hoping to accomplish in your OS program over the next 6 months?
* Attendee 1
	* Obstacle: procedure docs for how to dev software, then reality of how people dev software, then process to reconcile the two
		* Working w/policy people to refine the procedures (make them actually doable & effective)
* Attendee 2
	* OCTO, focused on SDLC
	* Centralisation of SDLC on central platform (GitLab)
	* Working on contribution policy & processes
		* Technical mechanisms, division specific approval & oversight
		* Make this more streamlined in next 6 months
	* Talk a bit about the pattern for this?
		* traceability (hyper-focused on segregation of duties between operations & development)
		* Need to be transparent what they're engaging with + have a review process
		* Setting up the plumbing for traceability & auditability
* Attendee 3
	* Architecture engineer
	* Have had handbooks/policies about this forever
		* Prefer commercially supported
	* People finally realising commercially supported isn't always an option
	* CIO asked for open source adoption policy, which he's working on
	* Preference right now is focus on inbound (most pressing at the moment)
	* Use Sonatype
	* Hard to find right legal people w/FOSS knowledge
	* Interested in talking to Wipro about helping
* Attendee 4
	* Has a bad audio connection
	* Trying to put "open source rule" in place
* FINOS survey
	* Walked through some slides from OSSF London

**Comment by gravax** [comment]
Can't validate the content, but this is quite clear and readable.
