### ISSUE TITLE
Incorrect meeting cadence on the website

### ISSUE THREAD

**Issue by vmbrasseur** [finos/open-source-readiness#6]
### Steps to Reproduce:

 1. https://www.finos.org/open-source-readiness and also https://www.finos.org/get-involved

> The group meets on a bi-weekly basis…

and 

>  A great first choice is our Open Source Readiness Project call that occurs every other Wednesday at 10am ET / 3pm BT.

### Expected Result:

OSR meets monthly.

**Comment by vmbrasseur** [comment]
Hey there, @grizzwolf. There's been no movement on this issue. Is there someone else we should get to work on it?

**Comment by psmulovics** [comment]
Actually now we meet twice a month :)

**Comment by caradelia** [comment]
Would @TheJuanAndOnly99 be able to help with this?
