### ISSUE TITLE
Open Source Maturity Model Feedback

### ISSUE THREAD

**Issue by mcleo-d** [finos/open-source-readiness#60]
Open Source Maturity Model URL - https://survey.osmm.finos.org/318556?lang=en

## Functional
Please add function issues to the OSMM FINOS Labs repo - https://github.com/finos-labs/osmm/issues
- Does everything work?

## Qualitative
Please add your Qualitative feedback to the comments of this GitHub issue ...

1. Is the OSMM helpful in understanding the state of open source at your organization?
   - How could it be made more useful?
  
2. Which questions within the dimensions and elements are most useful? Which are least useful?
   - Are there any key ones missing?

3. Was the workflow logical? What improvements could be made?
4. What other features would be helpful?
5. Are you able to use the outputs of the survey to:
   - Define the current state of maturity within your organization?
   - Define next steps for engaging the broader org (e.g. developers, BA's PM's) in terms of training, consumption, contribution activities?

Presentation Slides from #49 [OSMM presentation v4.0.pdf](https://github.com/finos/open-source-readiness/files/9505967/OSMM.presentation.v4.0.pdf)

**Comment by mcleo-d** [comment]
Thanks for pinning this issue @psmulovics 👍🏻

**Comment by mcleo-d** [comment]
![OSMM Questions Strategy Questions 1](https://user-images.githubusercontent.com/6029572/193866285-3cb68eb9-eb83-4f1e-86de-1a5ee81e31a6.png)

![OSMM Questions Strategy Questions 2](https://user-images.githubusercontent.com/6029572/193866312-f1e5ecf9-34ef-4939-ba82-0c97de7d8398.png)

[OSMM questions ver2.0.xlsx - Strategy Questions.pdf](https://github.com/finos/open-source-readiness/files/9708513/OSMM.questions.ver2.0.xlsx.-.Strategy.Questions.pdf)

**Comment by mcleo-d** [comment]
## OSMM Testing Feedback
- @mcleo-d working with Linux Foundation Legal on OSMM T&C. 
  - The existing Linux Foundation Data Privacy and GDPR policy needs specific context for the OSMM use of data.
  - @mcleo-d  meeting LF Legal on Thursday 6th October
- Banks have requested permission to view https://survey.osmm.finos.org/318556?lang=en from internal infrastructure teams. This has slowed progress testing the OSMM system.
- Banks have requested FINOS signs an NDA for the data inputted into the OSMM.
  - @mcleo-d suggested waiting for the LF T&Cs to be updated before pursuing this path.
  - **Question** - OSMM team to feedback whether bank NDAs would affect the purpose and use of the product?
- Banks have tested the OSMM and are awaiting internal approval to share the results. 

## OSMM Testing Mitigations
- Banks to test the OSMM workflow on a FINOS call with OSMM team sharing screen. 
  - Verbal, anonymised feedback will be collected as part of the group session.
  - Session to be arranged (if not done on OSR call)
- Banks to test questions in the comments of this issue - https://github.com/finos/open-source-readiness/issues/60#issuecomment-1267215407

**Comment by mcleo-d** [comment]
## OSMM Banking User Testing

Please find the output of the OSMM banking user testing below ...

https://github.com/finos/open-source-readiness/issues/67

**Comment by brooklynrob** [comment]
It would be useful if out of this effort (OSMM) or related efforts (maybe something out of TODO and/or CHAOSS) we could establish industry and cross-industry KPI benchmarks (e.g., mean, median, top 10%, top quartile, etc) and definitions for KPIs such as:

- Active Contributors.  # of employee-contributors contributing to OSS on behalf of their firm. This would need to include the definition of an active contributor, and what activities are counted as contribution activities (just code contribution? documentation contribution too? test case development? github issue creation and curation?). This in turn could be used to create a ratio of active contributors to total engineers to get a % of an engineering team/division that is actively contributing  (and the industry and cross-industry top 10%, top quartile, etc for those ratios, which would likely be more illustrative than the absolute numbers; i.e., the denominator of # of engineers at an org is important context)

- Active projects. # projects to which the org is actively contributing (during a specific time frame)

- Total # of PRs (and/or commits) made by org (per time period). To clarify, not expecting to see individual orgs' numbers, but the industry and cross-industry mean, median, top 10% cut-off, quartiles, etc for these.

- Contributed/Originated projects. Number of projects orgs have originated in their firm and in turn open sourced, either into their own GitHub org or as a contribution to a third-party (e.g., a foundation like FINOS)

- # of CCLAs an org has executed/entered and maintains

**Comment by jstclair2019** [comment]
Might want to consider closing this out as I think we'll spawn two efforts: 1) Technical feedback for improvements to the OSMM and repo and 2) Feedback and improvement to tailor the OSMM through the OSR BOK process

**Comment by robmoffat** [comment]
Closing, as OSMM work is moving in a different direction going forward.

Addressing @brooklynrob's comment, we have this page: https://osr.finos.org/docs/bok/Measurements/Organisation

And I've created this PR:

- #178 

for the KPI around CCLAs.
