### ISSUE TITLE
5th October 2022 - Open Source Readiness Meeting Agenda

### ISSUE THREAD

**Issue by mcleo-d** [finos/open-source-readiness#61]
## Date
Wednesday 5th October 2022 - 3pm UK / 10am ET

## Untracked attendees
- Fullname, Affiliation, (optional) GitHub username
- ...

## Meeting notices
- FINOS **Project leads** are responsible for observing the FINOS guidelines for [running project meetings](https://community.finos.org/docs/governance/meeting-procedures/). Project maintainers can find additional resources in the [FINOS Maintainers Cheatsheet](https://community.finos.org/docs/finos-maintainers-cheatsheet).

- **All participants** in FINOS project meetings are subject to the [LF Antitrust Policy](https://www.linuxfoundation.org/antitrust-policy/), the [FINOS Community Code of Conduct](https://community.finos.org/docs/governance/code-of-conduct) and all other [FINOS policies](https://community.finos.org/docs/governance/#policies). 

- FINOS meetings involve participation by industry competitors, and it is the intention of FINOS and the Linux Foundation to conduct all of its activities in accordance with applicable antitrust and competition laws. It is therefore extremely important that attendees adhere to meeting agendas, and be aware of, and not participate in, any activities that are prohibited under applicable US state, federal or foreign antitrust and competition laws. Please contact legal@finos.org with any questions.

- FINOS project meetings may be recorded for use solely by the FINOS team for administration purposes. In very limited instances, and with explicit approval, recordings may be made more widely available.

## Agenda
- [x] Convene & roll call (5mins)
- [x] Display [FINOS Antitrust Policy summary slide](https://community.finos.org/Compliance-Slides/Antitrust-Compliance-Slide.pdf) 
- [x] Review Meeting Notices (see above)
- [ ] Approve past meeting minutes
- [x] @vmbrasseur OSR SIG update.
- [x] **Feedback, Review and Discussion** : [FINOS Open Source Maturity Model ](https://survey.osmm.finos.org/318556?lang=en)
  - https://github.com/finos/open-source-readiness/issues/60
  - Proposing solutions to help overcome testing difficulties.
- [x] https://github.com/finos/open-source-readiness/issues/62
  - What is the FINOS OSPO roundtable?
  - Topic review and prioritisation.
- [x] AOB, Q&A & Adjourn (5mins)
  -  Open Source Readiness Project Booth at OSFF NYC on 8th December

### Minutes
- @vmbrasseur stepped down as OSR SIG lead. Thank you for your contribution and SIG leadership.
- OSR SIG raised internal policy and infrastructure blockers for OSMM testing.
- OSMM questions added to GitHub for banking review to mitigate issues above.
- OSR SIG invited to OSR OSPO roundtable in October.
- Topics of discussion introduced to the SIG, plus the reasons why the roundtable is for banks only.
- Open Source Readiness Project Booth introduced to the group for OSFF NYC on 8th December

### WebEx info
- Webex: https://finos.webex.com/finos/j.php?MTID=mec6bb47084d671bc772c0652add2605c
- Meeting number: 664 434 054

### Join by phone
- +1-415-655-0003 US Toll
- +44-20319-88141 UK Toll
- Access code: 664 434 054

**Comment by bingenito** [comment]
Brian Ingenito @ Morgan Stanley

**Comment by mcleo-d** [comment]
Hello 👋🏻

**Comment by cdeliaRH** [comment]
Hi 👋

**Comment by vmbrasseur** [comment]
Howdy 🤠

**Comment by BrittanyIstenes** [comment]
Hello all! Brittany Istenes - Fannie Mae OSPO Strategist

**Comment by mark-hoare-db** [comment]
Hi

**Comment by robmoffat** [comment]
Rob / FINOS

**Comment by pcheong-lbg** [comment]
Hello

**Comment by pholleran** [comment]
👋 - Phil from GitHub

**Comment by brooklynrob** [comment]
Rob from GS.

**Comment by ashyadav** [comment]
👋  Ash from HSBC
