### ISSUE TITLE
FINOS Banks Only OSPO Roundtable - October 27th at 2pm UK / 9am NYC

### ISSUE THREAD

**Issue by mcleo-d** [finos/open-source-readiness#62]
This issue has been created to list and prioritise the discussion topics for the **FINOS Banks Only OSPO Roundtable** on **October 27th at 2pm UK / 9am NYC**.

The OSPO roundtable will take place under Chatham House Rule, meaning participants are free to use the information received during the roundtable, but neither the identity nor the affiliation of the speaker(s), nor that of any other participant, will be revealed.

Also, in the essence of openness, anonymised content from the roundtable could be repurposed for use within Open Source Readiness. The content will be published by the FINOS team and will exclude the participant's details under Chatham House Rule.

Please submit ideas and priorities in the comments.

## Discussion Outcomes
- https://github.com/finos/open-source-readiness/issues/65
- https://github.com/finos/open-source-readiness/issues/66

**Comment by mcleo-d** [comment]
## InnerSource Licenses Required by Banks
Discussion chaired by @chamindra
  - The Case for InnerSource Licenses
  - Drawing Parallels from Open Source Licenses
  - Some Thoughts on InnerSource Rights Patterns

**Comment by robmoffat** [comment]
These are some topic ideas suggested by our colleagues at SocGen:

1.  Enterprise ‘Risk & Compliance’ framework
2. Code contribution 
3. Developer certification (Linux Foundation) 
4. Solving common industry problems (Ex : KYC, AML, Reconciliations etc.)

**Comment by robmoffat** [comment]
One from me:

_what are the main obstacles to employees contributing to open source projects from within the bank?_

If we compare _some large bank_ vs. _some large tech company_, why are the tech companies benefiting from / contributing to OSS in a greater way?

**Comment by cdeliaRH** [comment]
Many banks cannot access Github or Gitlab from work computers.

**Comment by mcleo-d** [comment]
The discussion outcomes from the roundtable can be found below ...

## Discussion Outcomes
- https://github.com/finos/open-source-readiness/issues/65
- https://github.com/finos/open-source-readiness/issues/66
