### ISSUE TITLE
Open nominations for OSR SIG co-chair!

### ISSUE THREAD

**Issue by psmulovics** [finos/open-source-readiness#63]
With @vmbrasseur leaving the role (I'd like to use this opportunity again to thank her for all the effort she poured into the OSR SIG's work), we have an empty co-chair role for the leadership of the OSR SIG.

We are looking for nominations in this issue as comments from the companies/candidates, so please let the flow of candidates going! :)

**Comment by cdeliaRH** [comment]
Is there a nomination process to refer to?

**Comment by psmulovics** [comment]
> Is there a nomination process to refer to? And requirements of the role?

Thank you for the question! The requirements are now being formed as part of #12 . The process is easy, you comment on this open issue :)

**Comment by cdeliaRH** [comment]
I would like to nominate myself then.

**Comment by psmulovics** [comment]
Requirements of the role, DRAFT:

- 	Shape and guide OSR strategy and goals
- 	Attend monthly meetings to plan and schedule speakers and topics, shape and guide the meeting format
- 	Participate in monthly planning meetings
- 	Jointly lead and organize discussions online and in meetings
- 	Contribute to the production of draft documents/deliverables of the SIG
- 	Review and manage issues and pull requests on the SIG GitHub
- 	Cultivate and grow OSR community, including being active on the mailing list, Slack channels, and other communication media

**Comment by psmulovics** [comment]
Nomination received in email from Elspeth Minty, RBC OSPO team, for the co-chair role
