### ISSUE TITLE
2nd November 2022 - Open Source Readiness Meeting Agenda

### ISSUE THREAD

**Issue by psmulovics** [finos/open-source-readiness#64]
## Date
Wednesday 2nd November 2022 - 2pm GMT / 10am ET

## Untracked attendees
- Fullname, Affiliation, (optional) GitHub username
- ...

## Meeting notices
- FINOS **Project leads** are responsible for observing the FINOS guidelines for [running project meetings](https://community.finos.org/docs/governance/meeting-procedures/). Project maintainers can find additional resources in the [FINOS Maintainers Cheatsheet](https://community.finos.org/docs/finos-maintainers-cheatsheet).

- **All participants** in FINOS project meetings are subject to the [LF Antitrust Policy](https://www.linuxfoundation.org/antitrust-policy/), the [FINOS Community Code of Conduct](https://community.finos.org/docs/governance/code-of-conduct) and all other [FINOS policies](https://community.finos.org/docs/governance/#policies). 

- FINOS meetings involve participation by industry competitors, and it is the intention of FINOS and the Linux Foundation to conduct all of its activities in accordance with applicable antitrust and competition laws. It is therefore extremely important that attendees adhere to meeting agendas, and be aware of, and not participate in, any activities that are prohibited under applicable US state, federal or foreign antitrust and competition laws. Please contact legal@finos.org with any questions.

- FINOS project meetings may be recorded for use solely by the FINOS team for administration purposes. In very limited instances, and with explicit approval, recordings may be made more widely available.

## Agenda
- [x] Convene & roll call (5mins)
- [x] Display [FINOS Antitrust Policy summary slide](https://community.finos.org/Compliance-Slides/Antitrust-Compliance-Slide.pdf) 
- [x] Review Meeting Notices (see above)
- [ ] Approve past meeting minutes
- [x] OSR SIG Co-chair update, https://github.com/finos/open-source-readiness/issues/63
- [x] Update on https://github.com/finos/open-source-readiness/issues/60
  - https://github.com/finos/open-source-readiness/issues/67
  - https://github.com/finos/open-source-readiness/issues/68
  - **Soft launch at OSFF NY on 8th December** 🚀 
- [x] Summary of https://github.com/finos/open-source-readiness/issues/62 by @mcleo-d 
  - https://github.com/finos/open-source-readiness/issues/65 
  - https://github.com/finos/open-source-readiness/issues/66
- [x] Open Source Readiness Project Booth at OSFF NYC on 8th December
- [x] AOB, Q&A & Adjourn (5mins)

### Minutes
- Update of OSR SIG co-chair recruitment given that includes the latest nominations.
- SIG taken through the OSMM testing feedback that was received by FINOS.
- No major issues to suggest OSMM should not be deployed.
- Feedback that was given can be added to the OSMM backlog and implemented after launch.
- SIG agreed to move forward with the OSMM beta implementation for OSFF in December.
- SIG taken through the GDPR policy and statement that's being constructed by LF legal.   
- SIG taken through the feedback from the October OSR roundtable.
- The OSR SIG was invited to have a project booth at OSFF on December 8th in NYC.

### WebEx info
- Webex: https://finos.webex.com/finos/j.php?MTID=mec6bb47084d671bc772c0652add2605c
- Meeting number: 664 434 054

### Join by phone
- +1-415-655-0003 US Toll
- +44-20319-88141 UK Toll
- Access code: 664 434 054

**Comment by mcleo-d** [comment]
Hello 👋🏻

**Comment by BrittanyIstenes** [comment]
Hello!

**Comment by psmulovics** [comment]
Peter Smulovics, Morgan Stanley, co-chair

**Comment by cdeliaRH** [comment]
Hello 👋 Cara, Red Hat

**Comment by robmoffat** [comment]
Rob / FINOS

**Comment by bingenito** [comment]
Brian Ingenito / Morgan Stanley

**Comment by brooklynrob** [comment]
Rob from GS

**Comment by brooklynrob** [comment]
I've added a [comment](https://github.com/finos/open-source-readiness/issues/60#issuecomment-1300565104) re my suggestion around KPI benchmarks and the OSMM.

**Comment by eteridvalishvili** [comment]
Eteri/FINOS

**Comment by HelloKay27** [comment]
Hi! Kay from Goldman Sachs
