### ISSUE TITLE
How have you automated your OSPO to minimise friction? - FINOS Banks Only OSPO RoundTable 27th October 2022

### ISSUE THREAD

**Issue by mcleo-d** [finos/open-source-readiness#66]
## How have you automated your OSPO to minimise friction?

- Everything in the OSPO is still manual: requests to contribute to open source are through tickets. We have a script to check our GitHub organisation against the firm active directory, but it doesn't remove them from GitHub yet. Developers who have left are removed from the GitHub organisation manually. Maintainers of our repos are all GitHub organisation members and members of their own teams. The FINOS CCLA is linked to our organisation through EasyCLA. When they leave the firm, we can remove them from the FINOS CLA tool (Linux Foundation's EasyCLA) through GitHub.

- A request was made within the group to be shown how EasyCLA can be maintained by using GitHub organisations and teams rather than manual lists as an EasyCLA manager.

- What is the industry definition, baseline and benchmark of an Active Contributor? It would be nice to get a benchmark of Active Contributors vs Total Engineers in the firm.

- In the regulated banking industry, organisations can’t scale beyond a few dozen, maybe a hundred open source Active Contributors without industry automation around CLAs. The open source community needs to figure out how a common API can add new contributors to CLAs across multiple foundations, organisations and independent projects. We also need to be vigilant about removing contributors after they leave the organisation. This is the friction that will stop banks from scaling, full stop.

- Example foundations where API calls should be used to approve and remove contributors include - Apache Software Foundation, Python Software Foundation, Linux Foundation, etc … We absolutely need to be vigilant about removing contributors from CCLAs and this can be ignored by foundations outside the Linux Foundation.

- This investment should be made by foundations through membership contributions. 

- For us, there is an issue around internal flexibility. Internally, we have a top-down ownership model, which makes governance of InnerSource and open source inflexible. Who really owns an InnerSource or open source project? When people leave we should notify their managers and find out if they should be allowed to continue to contribute. The internal governance models don’t align to InnerSource and open source models as projects need to bend and shift over time. Core teams need to change gradually or dramatically over a given period of time. CLAs and change requests are hitting the same governance models in banks.

- Information for others - Our model is not top-down. Engineers can choose to be contributors. We talked about aligning projects with departments and OKRs but decided against this. We have a single gate: a new contributor must take a course on legal, social and governance matters around open source and then provide their GitHub handle. So for example, if someone wants to contribute to say, Pandas, they take the course, provide their handle, we set up the CLA and they're good to go. 

- If a particular project is not on the approved CLA list, this gets routed to the OSPO and an OSPO team member will review the request, assess reputational risk and review discussions the bank wouldn’t want to be associated with. IP considerations and licence checks are done. CLAs are also set up if they don’t exist already. Several months can go by at the CLA stage alone.

- We do not use GitHub as a security entitlement group. We use GitLab and this is what our SDLC is based on. Our internal and external worlds need to be aligned from GitLab to GitHub.

- Executing CLAs through internal banking legal teams can take time through legal teams. CCLAs often don’t fall into the model that banks want to work with. The Linux Foundation isn’t so much of an issue through EasyCLA, but some CCLAs are more of a problem, such as Google that operates its CCLAs through Google Groups.

- We have the same issues with CCLAs (Corporate Contributor Licence Agreement). The internal risk review also takes a long time, although we're trying to streamline this for small contributions.

- It was suggested that a collaboration model, such as OpenSSF’s, could be used to bring open source entities together to resolve the cross open source industry CLA issue. OpenSSF is an example where the Linux Foundation has demonstrated an ability to work across other foundations and come up with something consistent. Would it be possible for us to convene a foundation within the LF to come up with an industry standard protocol? Bringing a critical mass of Apache Software Foundation, Python Software Foundation, large technology companies like Microsoft, Google, Meta, Linux Foundation. A common protocol for adding, removing contributors to CCLA schedule A’s will unlock contribution at scale within the financial services industry.

- The OSPO roundtable agrees that obtaining CCLAs for open source contribution is the top most point of friction. This often leads to KPIs being missed due to the lead time involved going through legal processes. Examples include tech firms who refuse to give physical copies of CCLAs for review. This has led to a 2 year delay contributing to their projects. The only versions are online at the point of pull request. Even screenshots aren’t possible.

- The pull request model of adding people to CLAs isn’t always the best model for banks. Adding people directly to the Schedule A, so there isn’t friction at the point of contribution is more in keeping with the way that banks would like to work. People give up as the process of contribution is too hard. People go back to working in their internal teams.

- Multiple banks +1’d the OSPO issue that was discussed. Multiple voices within the FINOS OSPO community magnified the issue and agreed this was something that needs to be taken forward and resolved. The solution at this stage still needs to be investigated, but it should be a cross industry solution, rather than a single open source foundation solving for their community only.

- The CCLA issue isn’t at the top of all banks' concerns, but it’s easy to see where it will become a concern in the future.

- Writing an RFP with examples for The Linux Foundation could help. Including API examples to move the conversation forward with all parties that need to be engaged on the solution. The group agreed to engage on this, with initial help from the FINOS team.

**Comment by robmoffat** [comment]
I'm self-assigning this so that I don't forget about it.  I think we'll need to think how to incorporate all this feedback into the body-of-knowledge structure.
