### ISSUE TITLE
FINOS Banks Only OSPO Roundtable at OSFF, NYC - December 8th at 4:15pm ET / 9:15am GMT

### ISSUE THREAD

**Issue by mcleo-d** [finos/open-source-readiness#69]
FINOS invites FINOS banking members to an OSPO roundtable for FINOS banks only that's taking place at the **FINOS Open Source in Finance Forum in NYC on December 8th**. 

Please register for in person attendance using your FINOS member registration code that's obtained by emailing [osff@finos.org](mailto:osff@finos.org) ... [https://events.linuxfoundation.org/open-source-finance-forum-new-york/register/](https://www.google.com/url?q=https://events.linuxfoundation.org/open-source-finance-forum-new-york/register/&sa=D&source=calendar&ust=1668354804462976&usg=AOvVaw07XfO0yAPWH-zWmbjSHHij)

This issue has been created to list and prioritise the discussion topics for FINOS banks only roundtable.

The OSPO roundtable will take place under Chatham House Rule, meaning participants are free to use the information received during the roundtable, but neither the identity nor the affiliation of the speaker(s), nor that of any other participant, will be revealed.

Also, in the essence of openness, anonymised content from the roundtable could be repurposed for use within Open Source Readiness. The content will be published by the FINOS team and will exclude the participant's details under Chatham House Rule.

Please submit ideas and priorities in the comments.

**Comment by mcleo-d** [comment]
@alvin-c-shih as asked on https://github.com/finos/kdb/issues/81 
  - What is the appetite for an AL/ML Ops Project or SIG amongst FINOS banks?

**Comment by mcleo-d** [comment]
## FINOS Banks Only OSPO Roundtable Agenda - 8th December at OSFF NYC

During the OSPO discussion we'll be focusing on Establishing an Open Source Readiness 2023 Strategy

As FINOS establishes an Open Source Readiness strategy for 2023, we invite your input into a strategy that spotlights OSR as a FINOS cornerstone offering to the Financial Services Industry.

During the roundtable we’ll be joined by Jim St Clair who will guide the discussion on topics such as …
- How to establish OSR training for banks and possible assessment certification.
- When are banks Open Source Ready and how can it be evaluated?
- What do you expect from OSR versus the Linux Foundation TODO Group?

**Comment by psmulovics** [comment]
#73 #74 #75 #76 #77 #78 #79 #80 #81

**Comment by robmoffat** [comment]
closing, since @psmulovics raised all of those issues, above
