### ISSUE TITLE
7th December 2022 - Open Source Readiness Meeting Agenda

### ISSUE THREAD

**Issue by psmulovics** [finos/open-source-readiness#71]
## Date
Wednesday 7th December 2022 - 2pm GMT / 10am ET

## Untracked attendees
- Elspeth Minty
- ...

## Meeting notices
- FINOS **Project leads** are responsible for observing the FINOS guidelines for [running project meetings](https://community.finos.org/docs/governance/meeting-procedures/). Project maintainers can find additional resources in the [FINOS Maintainers Cheatsheet](https://community.finos.org/docs/finos-maintainers-cheatsheet).

- **All participants** in FINOS project meetings are subject to the [LF Antitrust Policy](https://www.linuxfoundation.org/antitrust-policy/), the [FINOS Community Code of Conduct](https://community.finos.org/docs/governance/code-of-conduct) and all other [FINOS policies](https://community.finos.org/docs/governance/#policies). 

- FINOS meetings involve participation by industry competitors, and it is the intention of FINOS and the Linux Foundation to conduct all of its activities in accordance with applicable antitrust and competition laws. It is therefore extremely important that attendees adhere to meeting agendas, and be aware of, and not participate in, any activities that are prohibited under applicable US state, federal or foreign antitrust and competition laws. Please contact legal@finos.org with any questions.

- FINOS project meetings may be recorded for use solely by the FINOS team for administration purposes. In very limited instances, and with explicit approval, recordings may be made more widely available.

## Agenda
- [x] Convene & roll call (5mins)
- [x] Display [FINOS Antitrust Policy summary slide](https://community.finos.org/Compliance-Slides/Antitrust-Compliance-Slide.pdf) 
- [x] Review Meeting Notices (see above)
- [x] Approve past meeting minutes
- [x] OSR SIG Co-chair update, nominations and seconding of #63 
  - Cara Delia - Red Hat
  - Elspeth Minty - Royal Bank Canada
  - Brittany Istenes - Fannie Mae
- [x] Open Source Readiness Project Booth at OSFF NYC on 8th December
  - Take the [Open Source Maturity Model](https://survey.osmm.finos.org/551476) with Andrew Aitken from Wipro at the OSR booth at OSFF, NYC. 
- [x] #69 at OSFF
- [x] Discussing content of #68 
- [x] AOB, Q&A & Adjourn (5mins)

## Open Source Maturity Model Beta 

Take the OSMM survey here 👉🏻 https://survey.osmm.finos.org/551476

![Screenshot 2022-12-07 at 09 47 37](https://user-images.githubusercontent.com/6029572/206210099-980fdd48-0d01-42f1-a6fb-2e8d9a19e9e6.png)

## Minutes
- OSR SIG lead nominations and approvals done. Congratulations.
  - https://github.com/finos/open-source-readiness/issues/71#issuecomment-1341117337 
    - Cara Delia - Red Hat
    - Elspeth Minty - Royal Bank Canada
    - Brittany Istenes - Fannie Mae
- Details for Open Source Readiness Project Booth at OSFF NYC shared with the SIG
- Peter, Cara and Brittany to attend the project booth as will be at the NYC event.
- Andrew Aitken will attend the booth with SIG leads to represent OSMM.
- SIG introduced to OSR Roundtable schedule at OSFF in New York.
- The SIG agreed that Cara should attend roundtable as OSR lead.
- SIG introduced to deployed beta of OSMM and urged to take the survey.
- SIG introduced to https://github.com/finos/open-source-readiness/issues/68 and invited to feedback if required.
  
### WebEx info
- Webex: https://finos.webex.com/finos/j.php?MTID=mec6bb47084d671bc772c0652add2605c
- Meeting number: 664 434 054

### Join by phone
- +1-415-655-0003 US Toll
- +44-20319-88141 UK Toll
- Access code: 664 434 054

**Comment by caradelia** [comment]
Apologies for not being able to attend. I'm flying to NYC for OSFF during the mtg. Looking forward to seeing everyone!

**Comment by psmulovics** [comment]
hi!

**Comment by mcleo-d** [comment]
Hello 👋🏻

**Comment by RichardWagener365** [comment]
Hi - Richard @ Codethink

**Comment by robmoffat** [comment]
Rob / FINOS

**Comment by mcleo-d** [comment]
- Cara Delia (Red Hat) 
  - Nominated by Peter Smulovics of Morgan Stanley 
  - Seconded by Elspeth Minty of RBS 
- Elspeth Minty (RBC)
  - Nominated by Peter Smulovics of Morgan Stanley 
  - Seconded by Ash Yadav of HSBC 
- Brittany Istenes (Fannie Mae)
  - Nominated by Peter Smulovics of Morgan Stanley 
  - Seconded by Elspeth Minty of RBC

**Comment by psmulovics** [comment]
Congrats, @caradelia , Elspeth and @BrittanyIstenes !
