### ISSUE TITLE
03 Nov 2021 - Open Source Readiness Meeting Agenda

### ISSUE THREAD

**Issue by Julia-Ritter** [finos/open-source-readiness#8]
## Date
2021 Nov 08 - 10 am ET / 3 pm BST

## Untracked attendees
- Fullname, Affiliation, (optional) GitHub username
- ...

## Meeting notices
- FINOS **Project leads** are responsible for observing the FINOS guidelines for [running project meetings](https://github.com/finos/community/blob/master/governance/Meeting-Procedures.md#run-the-meeting). Project maintainers can find additional resources in the [FINOS Maintainers Cheatsheet](https://odp.finos.org/docs/finos-maintainers-cheatsheet/).

- **All participants** in FINOS project meetings are subject to the [LF Antitrust Policy](https://www.linuxfoundation.org/antitrust-policy/), the [FINOS Community Code of Conduct](https://github.com/finos/community/blob/master/governance/Code-of-Conduct.md) and all other [FINOS policies](https://github.com/finos/community/tree/master/governance#policies). 

- FINOS meetings involve participation by industry competitors, and it is the intention of FINOS and the Linux Foundation to conduct all of its activities in accordance with applicable antitrust and competition laws. It is therefore extremely important that attendees adhere to meeting agendas, and be aware of, and not participate in, any activities that are prohibited under applicable US state, federal or foreign antitrust and competition laws. Please contact legal@finos.org with any questions.

- FINOS project meetings may be recorded for use solely by the FINOS team for administration purposes. In very limited instances, and with explicit approval, recordings may be made more widely available.

## Agenda
- [x] Convene & roll call (5mins)
- [x] Display [FINOS Antitrust Policy summary slide](https://github.com/finos/community/blob/master/governance/Compliance-Slides/Antitrust-Compliance-Slide.pdf) 
- [x] Review Meeting Notices (see above)
- [x] Approve past meeting minutes
    - [x] [October 19](https://github.com/finos/open-source-readiness/issues/5)
    - [x] [September 01](https://github.com/finos/open-source-readiness/issues/4)
    - [x] [August 04](https://github.com/finos/open-source-readiness/issues/3)
- [x] Reminders
    - [x] December meeting (invite your lawyers & colleagues)
    - [x] [Discussion thread](https://github.com/finos/open-source-readiness/discussions/9) about regulators & open source
- [x] Guided discussion on contribution experiences & policies
- [x] AOB, Q&A, & Adjourn (5mins)

## Decisions Made
- [ ] Decision 1
- [ ] Decision 2
- [ ] ...

## Action Items
- [ ] Action 1
- [ ] Action 2
- [ ] ...

### WebEx info
- Webex: https://finos.webex.com/finos/j.php?MTID=mec6bb47084d671bc772c0652add2605c
- Meeting number: 664 434 054

### Join by phone
- +1-415-655-0003 US Toll
- +44-20319-88141 UK Toll
- Access code: 664 434 054

**Comment by Julia-Ritter** [comment]
Julia / FINOS

**Comment by jgavronsky** [comment]
Jane /FINOS

**Comment by gravax** [comment]
I'm on the call! From @Wipro.

**Comment by vmbrasseur** [comment]
Howdy 🤠 Wipro

**Comment by gyehuda** [comment]
Hello, I'm Gil I work at US Bank

**Comment by eduardosan** [comment]
Eduardo Santos / Itaú

**Comment by cdeliaRH** [comment]
Cara Delia, Red Hat, cdeliaRH

**Comment by KM210001** [comment]
I'm on the call! From Revenera...

**Comment by gravax** [comment]
The link I mentioned from Societe Generale and their talent attraction part of their open source strategy: https://www.societegenerale.com/en/societe-generale-group/strategy/innovation-and-digital

**Comment by vmbrasseur** [comment]
Attending: VMB, Gilles Gravier, Aaron Williamson, Cara Delia (RH), Eduardo F. Santos (Itaú), Julia (FINOS), Gil Yehuda, Jane Gavronsky (FINOS), Kendra Morton (Revenera), Sergio Rojas (Academy Software Foundation), Simon Holt (JP Morgan), Girish Ahuja (SMBC)

* Antitrust
* CHR
* Dec 1: Bring your lawyer to OSR Day
* Round of introductions
* Approved meeting minutes
* Reminders
	* December
	* Discussion thread #9
		* Person 1: encouraging others to join the discussion
		* Person 1: thanks to FINOS for facilitating that discussion w/regulators
		* Person 2: Made a plug for the conversation at the Reg Innovation SIG
* Contribution policies
	* Do you have one?
		* Person 1: Yes, but evolving (current is 'bias to block')
		* Person 1: Internally try not to use "contribution" because it sounds like charity
			* Focus on upstream fixes
		* Person 3: Almost never the case that it's "just because"
	* Person 4: w/history at their bank
		* 2 years ago was forbidden at the org
		* Couldn't use anything that didn't have a paid subscription
		* Now can use open source, but can't contribute using your work account
			* Very regulated work day; logging hours on specific projects
			* FOSS contributions don't fit into that framework
			* But if they need to contribute for their jobs…?
			* Had to do it outside of the office, on personal time & account
		* Changed that 2 months ago
			* Was losing developers because they weren't allowed to contribute
			* Can contribute using bank account on work hours w/manager authorisation
			* Don't have the process yet, though
			* Strong labour law about working out of work hours
		* Currently: getting people who have done contributions & having them help inside the bank
		* Trying to structure something to present to us soon
		* Person 5: The policy for _any_ project or approved only and are there code reviews, or…?
			* Will be a case by case basis
			* No blanket approval or approved/disapproved list
			* OSPO sponsors the contribution
			* Must be a business person who approves that it makes sense for the business
			* Use git-proxy internally to see whether it'll work for their contributions
			* Person 2: Goldman-Sachs recently contributed a tool to catch secrets before they get contributed
	* Co-chair: Person 6, what are you hearing at your company?
		* Desire to have OSPO for attracting new talent
		* Once they get the talent, work with Legal about how they contribute
		* Also hearing a lot about where to even begin
		* Looking a lot at InnerSource and looking at that to be able to understand how to contribute to FOSS more strategically (no OSPOs)
			* Have an ISPO first; easier with regulations in their provinces
		* Showing them the value of sharing and contributing and building the ecosystem
		* Very interested in Environmental Sustainable Governance (ESG): Everyone is in the same boat
			* Data points are hard to get consistent
			* Looking at ESG project communities help a lot
* AOB
	* Future topics?
		* Person 5: To go with policy document, need a how-to guide for it including tooling; discuss how people manage that?
			* Person 3: Would need multiple people presenting
			* Person 7: Panel discussion and/or doc of best/common practices
				* Person 7 will chat with Person 5
		* Co-chair: add ideas to mailing list, slack, create GH issues

### AIs

* Person 1 will start a discussion about decomposing FOSS into different types

**Comment by Julia-Ritter** [comment]
Untracked attendees: 

- James Mcleod / FINOS
-  Simon Holt / JP Morgan
- Girish Ahuja / SMBC
