### ISSUE TITLE
OSR Developer Training

### ISSUE THREAD

**Issue by psmulovics** [finos/open-source-readiness#80]
"Certified open source (security) practicer"

How to establish osr training for banks and assessment / certification

**Comment by robmoffat** [comment]
For certification see:
- #123

**Comment by robmoffat** [comment]
Renamed to focus on developer training, which is currently underway.

Materials: https://drive.google.com/drive/folders/1-7qsl5VDsbF-3YvDT9XUQa9_n03QQcFS
