### ISSUE TITLE
4th January 2023 - Open Source Readiness Meeting Agenda

### ISSUE THREAD

**Issue by psmulovics** [finos/open-source-readiness#82]
## Date
Wednesday 4th January 2023 - 2pm GMT / 10am ET

## Untracked attendees
- ...

## Meeting notices
- FINOS **Project leads** are responsible for observing the FINOS guidelines for [running project meetings](https://community.finos.org/docs/governance/meeting-procedures/). Project maintainers can find additional resources in the [FINOS Maintainers Cheatsheet](https://community.finos.org/docs/finos-maintainers-cheatsheet).

- **All participants** in FINOS project meetings are subject to the [LF Antitrust Policy](https://www.linuxfoundation.org/antitrust-policy/), the [FINOS Community Code of Conduct](https://community.finos.org/docs/governance/code-of-conduct) and all other [FINOS policies](https://community.finos.org/docs/governance/#policies). 

- FINOS meetings involve participation by industry competitors, and it is the intention of FINOS and the Linux Foundation to conduct all of its activities in accordance with applicable antitrust and competition laws. It is therefore extremely important that attendees adhere to meeting agendas, and be aware of, and not participate in, any activities that are prohibited under applicable US state, federal or foreign antitrust and competition laws. Please contact legal@finos.org with any questions.

- FINOS project meetings may be recorded for use solely by the FINOS team for administration purposes. In very limited instances, and with explicit approval, recordings may be made more widely available.

## Agenda
- [x] Convene & roll call (5mins)
- [x] Display [FINOS Antitrust Policy summary slide](https://community.finos.org/Compliance-Slides/Antitrust-Compliance-Slide.pdf) 
- [x] Review Meeting Notices (see above)
- [ ] Approve past meeting minutes
- [x] Discuss the list of takeaways from the #69 , add to them if needed
- [x] Jim St Clair presentation of combined OSR SIG Strategy and FINOS 2023 Strategy for Q1 board meeting
- [x] Discuss suggestion of double cadence - meeting and workgroup
- [x] Discuss the plan for 2023 for OSFF
- [x] Discuss the update on Open Source Good Governance Handbook by The OSPO Alliance ( https://ospo.zone/ggi )
- [ ] AOB, Q&A & Adjourn (5mins)

### Zoom Details
- https://zoom.us/j/99753528440?pwd=OEFPWkQzLy9hWlV4NmM0RC9VRjhwQT09
- **Meeting ID:** 997 5352 8440
- **Passcode:** 987996

### Join by Phone
- Find your local number: https://zoom.us/u/adl5rhui4P

### Minutes
- Talking points from #69 shared with group. 
- FINOS OSR strategy presentation for Q1 board meeting done by Jim St Clair
- OSR group invited to comment and feedback through FINOS channels
- FINOS clarified that strategy was presented to OSR SIG leads prior to SIG meeting
- Presentation includes OSMM that was contributed to FINOS by Wipro
- Presentation also includes OSR training and body of knowledge available to members and non-members alike
- Question raised about having banks OSR maturity in the open. This was responded with GDPR feedback.
- Some banks might be happy with results in the open, where others are not.
- OSMM might be available to members only due to infra and maintenance costs.
- Anonymous OSMM results could appear in State of Open Source in Finance Survey
- Industry benchmarking was called out as very important
- Cadence of OSR increased to every 2 weeks.
- 2nd meeting needs to be specific and maybe shorter.
- Creating milestones for OSR that include OSFF in London and New York is beneficial.
- Using OSMM results for State of OSS in Finance was agreed to be taken away and discussed.

**Comment by bingenito** [comment]
Brian Ingenito / Morgan Stanley

**Comment by caradelia** [comment]
👋 Cara Delia - Red Hat

**Comment by pholleran** [comment]
👋 - Phil from GitHub

**Comment by BrittanyIstenes** [comment]
Hello!  Brittany from Fannie Mae here.

**Comment by mashby2022** [comment]
Maria Ashby - Non affiliated

**Comment by mcleo-d** [comment]
Hello 👋🏻

**Comment by robmoffat** [comment]
Rob / FINOS

**Comment by ColinEberhardt** [comment]
Colin Eberhardt / Scott Logic

**Comment by psmulovics** [comment]
Peter Smulovics / Morgan Stanley

**Comment by mvdietz** [comment]
Matt Dietz - BNY Mellon

**Comment by jstclair2019** [comment]
Jim/ FINOS

**Comment by stackedsax** [comment]
Alex Scammon / G-Research

**Comment by andybs** [comment]
Andy Smith / Discover
