### ISSUE TITLE
Pulling out as a separate issue for OSMM

### ISSUE THREAD

**Issue by caradelia** [finos/open-source-readiness#84]
It would be useful if out of this effort (OSMM) or related efforts (maybe something out of TODO and/or CHAOSS) we could establish industry and cross-industry KPI benchmarks (e.g., mean, median, top 10%, top quartile, etc) and definitions for KPIs such as:

- Active Contributors.  # of employee-contributors contributing to OSS on behalf of their firm. This would need to include the definition of an active contributor, and what activities are counted as contribution activities (just code contribution? documentation contribution too? test case development? github issue creation and curation?). This in turn could be used to create a ratio of active contributors to total engineers to get a % of an engineering team/division that is actively contributing  (and the industry and cross-industry top 10%, top quartile, etc for those ratios, which would likely be more illustrative than the absolute numbers; i.e., the denominator of # of engineers at an org is important context)

- Active projects. # projects to which the org is actively contributing (during a specific time frame)

- Total # of PRs (and/or commits) made by org (per time period). To clarify, not expecting to see individual orgs' numbers, but the industry and cross-industry mean, median, top 10% cut-off, quartiles, etc for these.

- Contributed/Originated projects. Number of projects orgs have originated in their firm and in turn open sourced, either into their own GitHub org or as a contribution to a third-party (e.g., a foundation like FINOS)

- number of CCLAs an org has executed/entered and maintains

_Originally posted by @brooklynrob in https://github.com/finos/open-source-readiness/issues/60#issuecomment-1300565104_

**Comment by psmulovics** [comment]
Related to #77

**Comment by robmoffat** [comment]
See:  https://osr.finos.org/docs/bok/Measurements/Organisation
