### ISSUE TITLE
Topic Allocation for OSR BoK

### ISSUE THREAD

**Issue by robmoffat** [finos/open-source-readiness#86]
Based on this article: https://osr.finos.org/docs/playbook/risk-based-view

Can we figure out who would be the right person to "own" each of these risks?  (From the point of view of capturing the state of the body-of-knowledge on that subject) 

Please comment below on the areas of expertise you have, and then we can figure out allocations for each one!

### Update 9th March 2023

We've made some significant progress on this over the last couple of weeks:  created placeholders for most of the articles we've identified in the SIG meetings, done a gap analysis of this with the [TODO Mind Map](https://ospomindmap.todogroup.org) and I'm going through the OW2 activities right now too.  

_That doesn't mean I haven't missed anything:  I'm expecting we'll see some more topics arise in the OSR SIG sessions._

Placeholder docs are created in this PR:

- #108 

Here is the breakdown of topics, with owners (people who've put up their hand to do some work on them) (master is [here](https://docs.google.com/spreadsheets/d/1o1_skz3Sv74bnSY1vsYWXLCsIERcKhV1Q3GqM4E90kc/edit#gid=1533178698))

| Category     | Subject                                                                  | Author                            | Status                                 |
|--------------|--------------------------------------------------------------------------|-----------------------------------|----------------------------------------|
| Artifacts    |                                                                          |                                   |                                        |
|              | Open Source Policy                                                       | Peter S                           | work in GDoc                           |
|              | Legislation (CRA)                                                        |                                   |                                        |
|              | SBOMs                                                                    | RM                                | V1 Complete                            |
|              | Licenses                                                                 | RM                                | V1 Complete                            |
|              | CLA / DCO                                                                | RM                                | V1 Complete                            |
|              | Open Source Strategy                                                     |                                   | placeholder                            |
|              | Patents                                                                  |                                   | placeholder                            |
|              |                                                                          |                                   |                                        |
| Measurements | Metrics - break these out? /ROI                                          | Jim                               | PR incoming                            |
|              |                                                                          |                                   |                                        |
| Roles        | CEO                                                                      | Cara to start                     | Placeholder                            |
|              | CIO-CTO                                                                  |                                   | Placeholder                            |
|              | Developer                                                                |                                   | Placeholder                            |
|              | HR-Training/Talent Mgmt                                                  |                                   | Placeholder                            |
|              | Legal                                                                    |                                   | Placeholder                            |
|              | OSPO                                                                     |                                   | Placeholder                            |
|              | OSRB                                                                     |                                   | Placeholder                            |
|              | Product-Manager                                                          |                                   | Placeholder                            |
|              | Risk-Officer                                                             |                                   | Placeholder                            |
|              | Security-Expert                                                          |                                   | Placeholder                            |
|              |                                                                          |                                   |                                        |
| Risks        |                                                                          |                                   |                                        |
|              | Outbound Security Risks                                                  |                                   |                                        |
|              | Inbound Securty Risks                                                    |                                   |                                        |
|              | Upside Risks - add these                                                 | RM (based on existing stuff)      |                                        |
|              | Codebase Risk                                                            |                                   | We have materials, just need to format |
|              | Data Leakage Risk                                                        |                                   | notes from Rhyddian                    |
|              | Dependency RIsk                                                          |                                   |                                        |
|              | Financial Risk                                                           |                                   | notes from Rhyddian                    |
|              | Legal Risks                                                              |                                   | notes from Rhyddian                    |
|              | Staff Risks                                                              |                                   | notes from Rhyddian                    |
|              |                                                                          |                                   |                                        |
| Activities   |                                                                          |                                   |                                        |
| Level 1      | Choosing And Using Open Source Software (Consuming)                      | Madlen Wilmes                     | Placeholder                            |
|              |                                                                          |                                   |                                        |
| Level 2      | inventory                                                                | Asking Mark/Sally at DB           | Placeholder                            |
|              | License Management                                                       | RM                                | Done                                   |
|              | Traning                                                                  |                                   | Placeholder                            |
|              | Open Source Supply Chain Security Training                               | Jim                               | Some written                           |
|              | Creating an Open Source Policy                                           | Peter S                           | work in GDoc                           |
|              | Working With Compliance                                                  |                                   | placeholder                            |
|              | Creating an OSPO                                                         | Pooi                              | placeholder                            |
|              |                                                                          |                                   |                                        |
| Level 3      | Contirbuting / Making the Case for Contribution                          | Elspeth                           | placeholder                            |
|              | Developing in Public                                                     |                                   | Placeholder                            |
|              | Data Leakage Prevention / Workflows / PRs                                | RM                                | RM to compile existing stuff           |
|              | Managing Open Source Talent                                              | Jim                               | Placeholder                            |
|              | Open Source Culture / ISPO                                               | Andy (Discover) / Aronya (Lloyds) | Placeholder                            |
|              |                                                                          |                                   |                                        |
| Level 4      | Contributing a Project                                                   | Jim                               | Placeholder                            |
|              | Vulnerability Disclosure / Outbound Security                             |                                   | placeholder                            |
|              | Maintaining a project                                                    |                                   | placeholder                            |
|              | Open Source Marketing / Community Engagement - cookbook? Discoverability | Vicki / Brittany                  | Placeholder                            |
|              | Interacting with Foundations                                             |                                   | Placeholder                            |
|              |                                                                          |                                   |                                        |
| Level 5      | Leveraging Open Source as a Strategy                                     |                                   | placeholder                            |
|              | Sponsorship                                                              |                                   |                                        |
|              |                                                                          |                                   |                                        |
| Other        | Reference Tool Set - add into each article                               | Thomas Steenberger?               |                                        |
| Cross Check: | OSPO Alliance Stuff                                                      | RM to reconcile                   |                                        |

**Comment by BrittanyIstenes** [comment]
I can help within: 

- License compliance and working with legal 
- Education 
- Talent retention

**Comment by caradelia** [comment]
Sorry for not replying sooner. I was out Thursday and Friday. In looking at the link, I see there being overlap in motivations, goals, etc. Are you all ok if I create a template to start mapping these to the different personas and we - along with the people identified from the firms- populate. I have attached a sample of something similar to what I have done before. https://docs.google.com/presentation/d/1PPS1cmS3NlEC7o6u3iCCcMva0EzVDP85EqGkzykuZsc/edit?usp=sharing

**Comment by jstclair2019** [comment]
Hi @caradelia I like the idea too, though I had to request access to the G Doc

**Comment by caradelia** [comment]
[FINOS Personas.pptx](https://github.com/finos/open-source-readiness/files/10482974/FINOS.Personas.pptx)
Try this @jstclair2019

**Comment by robmoffat** [comment]
absolutely - go for it.   I've given everyone access to this FINOS shared folder on Google Docs - perhaps we can stow everything in there for easy access?  

https://drive.google.com/drive/u/1/folders/1uva_EhNIn4Q_We6U0sa9fevTwR4dIxsN

(I've made a copy of the personas sheet already)

**Comment by caradelia** [comment]
Brilliant. Thanks Rob!

**Comment by jstclair2019** [comment]
Hi @caradelia I like the idea too, though I had to request access to the G Doc

**Comment by robmoffat** [comment]
@jstclair2019 and I have been working in our last couple of meetings to put together a list of docs in the [project plan](https://docs.google.com/spreadsheets/d/1o1_skz3Sv74bnSY1vsYWXLCsIERcKhV1Q3GqM4E90kc/edit#gid=1533178698)

I've listed what we have in the top of this issue so that people without Google access can see it.

Still probably we have things to have.   @jstclair2019 and I are working on finding authors for most of the bits.  It's a bit cobbled together but hopefully we have everyone down on here?  Please check and let me know if there's something you want to work on that I don't have your name against 🙏

**Comment by jstclair2019** [comment]
Andy Smith at DFS has a nice model they're building that he wants to share as well that should fit nicely

**Comment by psmulovics** [comment]
Update for the table above:

  |   |   |  
-- | -- | -- | --
Category | Subject | Author | Status
Artifacts |   |   |  
  | Open Source Policy | Peter S | work in GDoc
  | Legislation (CRA) |   |  
  | SBOMs | RM | V1 Complete
  | Licenses | RM | V1 Complete
  | CLA / DCO | RM | V1 Complete
  | Open Source Strategy |   | placeholder
  | Patents |   | placeholder
  |   |   |  
Measurements | Metrics - break these out?  /ROI | Jim - 3/20? | PR incoming
  |   |   |  
Roles | CEO | Cara to start | Placeholder
  | CIO-CTO | Cara to start | Placeholder
  | Developer | Cara to start | Placeholder
  | HR-Training/Talent Mgmt | Cara to start | Placeholder
  | Legal | Cara to start | Placeholder
  | OSPO | Cara to start | Placeholder
  | OSRB | Cara to start | Placeholder
  | Product-Manager | Cara to start | Placeholder
  | Risk-Officer | Cara to start | Placeholder
  | Security-Expert | Cara to start | Placeholder
  |   |   |  
Risks |   |   |  
  | Outbound Security Risks |   |  
  | Inbound Securty Risks |   |  
  | Upside Risks - add these | RM (based on existing stuff) |  
  | Codebase Risk |   | We have materials, just need to format
  | Data Leakage Risk |   | notes from Rhyddian
  | Dependency RIsk |   |  
  | Financial Risk |   | notes from Rhyddian
  | Legal Risks |   | notes from Rhyddian
  | Staff Risks |   | notes from Rhyddian
  |   |   |  
Activities |   |   |  
Level 1 | Choosing And Using Open Source Software (Consuming) | Madlen Wilmes | Placeholder
  | Managing Open Source-based Projects |   | Placeholder
  |   |   |  
Level 2 | inventory | Asking Mark/Sally at DB | Placeholder
  | License Management | RM | Done
  | Traning | Kay | Placeholder
  | Open Source Supply Chain Security Training | Jim | Some written
  | Creating an Open Source Policy | Peter S | work in GDoc
  | Working With Compliance | Andy Smith / Rob / Jim | placeholder
  | Creating an OSPO | Pooi | placeholder
  |   |   |  
Level 3 | Contirbuting / Making the Case for Contribution | Elspeth (After QCOn) | placeholder
  | Developing in Public |   | Placeholder
  | Data Leakage Prevention / Workflows / PRs | RM | RM to compile existing stuff
  | Managing Open Source Talent | Jim | Placeholder
  | Open Source Culture / ISPO | Andy (Discover) / Aronya (Lloyds) | Placeholder
  | Interacting with Foundations |   | Placeholder
  | Open Source Marketing / Community Engagement - cookbook? Discoverability | Vicki / Brittany | Placeholder
  |   |   |  
Level 4 | Contributing a Project | Jim | Placeholder
  | Vulnerability Disclosure / Outbound Security | Mao / Joss | placeholder
  | Maintaining a project |   | placeholder
  |   |   |  
Level 5 | Leveraging Open Source as a Strategy | Andrew / Gil | placeholder
  |   |   |  
Other | Reference Tool Set - add into each article | Thomas Steenbergen? |  
Cross Check: | OSPO Alliance Stuff | RM | V1 complete

**Comment by robmoffat** [comment]
Closing this - we have a few outstanding topics but the scope is really beyond a GitHub markdown table now.
