### ISSUE TITLE
Page Not Found for OSR Resources to Contribute to

### ISSUE THREAD

**Issue by caradelia** [finos/open-source-readiness#88]
### Steps to Reproduce:
 1. osr.finos.org
 2. Under Get Involved
 3. Click "resources" in the copy of "Contribute to our resources for open source programs"

### Expected Result:
Seeing resources to contribute to

### Actual Result:
**Page Not Found**
Looks like you've followed a broken link or entered a URL that doesn't exist on this site.

[ Back to our site](https://osr.finos.org/)

If this is your site, and you weren't expecting a 404 for this path, please visit Netlify's ["page not found" support guide](https://answers.netlify.com/t/support-guide-i-ve-deployed-my-site-but-i-still-see-page-not-found/125?utm_source=404page&utm_campaign=community_tracking) for troubleshooting tips.

**Comment by psmulovics** [comment]
Sadly due to a previous restructure of the documents, we have a few dead links around. Moving to docosaurus v2 hopefully will help with this too - eg both we would touch most content, and also hopefully change all references to use internal link resolution
