### ISSUE TITLE
1st February 2023 - Open Source Readiness Meeting Agenda

### ISSUE THREAD

**Issue by psmulovics** [finos/open-source-readiness#90]
## Date
Wednesday 1st February 2023 - 2pm GMT / 10am ET

## Untracked attendees
- Fullname, Affiliation, (optional) GitHub username
- ...

## Meeting notices
- FINOS **Project leads** are responsible for observing the FINOS guidelines for [running project meetings](https://community.finos.org/docs/governance/meeting-procedures/). Project maintainers can find additional resources in the [FINOS Maintainers Cheatsheet](https://community.finos.org/docs/finos-maintainers-cheatsheet).

- **All participants** in FINOS project meetings are subject to the [LF Antitrust Policy](https://www.linuxfoundation.org/antitrust-policy/), the [FINOS Community Code of Conduct](https://community.finos.org/docs/governance/code-of-conduct) and all other [FINOS policies](https://community.finos.org/docs/governance/#policies). 

- FINOS meetings involve participation by industry competitors, and it is the intention of FINOS and the Linux Foundation to conduct all of its activities in accordance with applicable antitrust and competition laws. It is therefore extremely important that attendees adhere to meeting agendas, and be aware of, and not participate in, any activities that are prohibited under applicable US state, federal or foreign antitrust and competition laws. Please contact legal@finos.org with any questions.

- FINOS project meetings may be recorded for use solely by the FINOS team for administration purposes. In very limited instances, and with explicit approval, recordings may be made more widely available.

## Agenda
- [x] Convene & roll call (5mins)
- [x] Display [FINOS Antitrust Policy summary slide](https://community.finos.org/Compliance-Slides/Antitrust-Compliance-Slide.pdf) 
- [x] Review Meeting Notices (see above)
- [x] Approve past meeting minutes
- [x] OSR Administrative Updates w/ @mcleo-d , @robmoffat 
- [x] Developer Training Course Materials w/ @rhyddian and @robmoffat 
- [x] Update from the working group session w/ @caradelia , @psmulovics 
- [x] Inviting people to the working group sessions
- [x] Executive Sponsorship for the initiative w/ @chrisjstevo
- [x] Creating a github org documentation w/ @eminty69 
- [ ] AOB, Q&A & Adjourn (5mins)

### Zoom Details
- https://zoom.us/j/99753528440?pwd=OEFPWkQzLy9hWlV4NmM0RC9VRjhwQT09
- **Meeting ID:** 997 5352 8440
- **Passcode:** 987996

### Join by Phone
- Find your local number: https://zoom.us/u/adl5rhui4P

**Comment by jstclair2019** [comment]
Probably want to give a quick update following last week's GB meeting

**Comment by bingenito** [comment]
Brian Ingenito / Morgan Stanley

**Comment by pholleran** [comment]
👋 - Phil from GitHub

**Comment by mcleo-d** [comment]
Hey all 👋🏻

**Comment by rhyddian** [comment]
Rhyddian Olds from Citi

**Comment by robmoffat** [comment]
Hello! Rob / FINOS

**Comment by jstclair2019** [comment]
Howdy y'all!

**Comment by caradelia** [comment]
Hello! Cara from Red Hat

**Comment by pcheong-lbg** [comment]
Hello. Pooi from Lloyds

**Comment by vickiychung** [comment]
Morning! Vicki from Goldman Sachs

**Comment by psmulovics** [comment]
Hello!

**Comment by mark-hoare-db** [comment]
Hi, Mark Hoare from Deutsche Bank

**Comment by eminty69** [comment]
Hello, Elspeth from RBC !

**Comment by ColinEberhardt** [comment]
Apologies, I wasn't able to attend today. I'm pretty sure in one of our previous meetings there was a discussion around making better use of the [State of Open Source in Finance 2022](https://www.linuxfoundation.org/research/the-2022-state-of-open-source-in-financial-services?hsLang=en) report findings. Perhaps by having a tailored presentation within FINOS member organisations. I was one of the report authors, if there is interest from anyone in this group, give me a shout. I'd be happy to work together to create something you can hopefully use within your org.

**Comment by jstclair2019** [comment]
@ColinEberhardt I think that's an excellent idea. I'll Slack you and we can discuss what we extract from the report as salient points to include in our strategy.
