### ISSUE TITLE
OSMM project/repo moved to project in FINOS

### ISSUE THREAD

**Issue by jstclair2019** [finos/open-source-readiness#91]
I can't find any reference to the OSMM in OSR or the FINOS repo. Was this intentional?

**Comment by psmulovics** [comment]
It's more a timing thing. It was announced at OSFF, and we did not wanted to edit the site around showtime.  The actual repo is at https://github.com/finos-labs/osmm and the site at https://survey.osmm.finos.org/551476

**Comment by jstclair2019** [comment]
@psmulovics I personally agree. We're looking like we'll be collaborating with LBG for the nest iteration of the OSMM and should be aligned to our other projects in OSR

**Comment by robmoffat** [comment]
there's a link in the footer...
