### ISSUE TITLE
Should OSR BOK be instantiated as an OSR project in GH

### ISSUE THREAD

**Issue by jstclair2019** [finos/open-source-readiness#92]
Decision on one or more repos for BOK.
I think we need to articulate a "dev" and "prod" location. I suspect the microsite hosts the "prod" version, but where best to build the library of content in "dev"?

**Comment by psmulovics** [comment]
So we are using netlify to generate a short living copy of the site for each PR - this can easily work for the BOK too

**Comment by jstclair2019** [comment]
Thanks @psmulovics - I'll close this issue

**Comment by jstclair2019** [comment]
I'm going to close this one - @robmoffat has a MD construct that we're building now
