### ISSUE TITLE
15th February 2023 - Open Source Readiness Workgroup Meeting Agenda

### ISSUE THREAD

**Issue by psmulovics** [finos/open-source-readiness#95]
## Date
Wednesday 15th February 2023 - 2pm GMT / 10am ET

## Untracked attendees
- Fullname, Affiliation, (optional) GitHub username
- ...

## Meeting notices
- FINOS **Project leads** are responsible for observing the FINOS guidelines for [running project meetings](https://community.finos.org/docs/governance/meeting-procedures/). Project maintainers can find additional resources in the [FINOS Maintainers Cheatsheet](https://community.finos.org/docs/finos-maintainers-cheatsheet).

- **All participants** in FINOS project meetings are subject to the [LF Antitrust Policy](https://www.linuxfoundation.org/antitrust-policy/), the [FINOS Community Code of Conduct](https://community.finos.org/docs/governance/code-of-conduct) and all other [FINOS policies](https://community.finos.org/docs/governance/#policies). 

- FINOS meetings involve participation by industry competitors, and it is the intention of FINOS and the Linux Foundation to conduct all of its activities in accordance with applicable antitrust and competition laws. It is therefore extremely important that attendees adhere to meeting agendas, and be aware of, and not participate in, any activities that are prohibited under applicable US state, federal or foreign antitrust and competition laws. Please contact legal@finos.org with any questions.

- FINOS project meetings may be recorded for use solely by the FINOS team for administration purposes. In very limited instances, and with explicit approval, recordings may be made more widely available.

## Agenda
- [ ] Convene & roll call (5mins)
- [ ] Display [FINOS Antitrust Policy summary slide](https://community.finos.org/Compliance-Slides/Antitrust-Compliance-Slide.pdf) 
- [ ] Review Meeting Notices (see above)
- [ ] License mgmt PR review ( #89 )
- [ ] Working on personas ( [working document](https://docs.google.com/document/d/1rbSsXFQVWn-whKAtCblsZv6VhRZBc6FBzo69o0edwK4/edit?usp=drivesdk) )
- [ ] Consider License Change for the GitHub project to match CC-BY-4.0 (as used by other documentation projects e.g. TODO group)
- [ ] AOB, Q&A & Adjourn (5mins)

## Decisions Made
- [ ] Decision 1

## Action Items
- [ ] Action 1

### Zoom Details
- https://zoom.us/j/99753528440?pwd=OEFPWkQzLy9hWlV4NmM0RC9VRjhwQT09
- **Meeting ID:** 997 5352 8440
- **Passcode:** 987996

### Join by Phone
- Find your local number: https://zoom.us/u/adl5rhui4P

**Comment by jstclair2019** [comment]
I'll have a table/worksheet for discussion that will provide an overview of roles/personas/responsibilities to stimulate discussion.

**Comment by mark-hoare-db** [comment]
Apologies, won't be able to attend this one

**Comment by bingenito** [comment]
Brian Ingenito / Morgan Stanley

**Comment by robmoffat** [comment]
Rob / FINOS

**Comment by pcheong-lbg** [comment]
Pooi / LBG

**Comment by eminty69** [comment]
Elspeth from RBC CM

**Comment by psmulovics** [comment]
Peter Smulovics / Morgan Stanley & OSR chair

**Comment by chrisjstevo** [comment]
Chris Stevenson / UBS

**Comment by HelloKay27** [comment]
Kay / Goldman Sachs

**Comment by rhyddian** [comment]
👋 Rhyddian Olds @ Citi.

**Comment by BrittanyIstenes** [comment]
Brittany Istenes - Fannie Mae

**Comment by awaiken** [comment]
andrew aitken

**Comment by abacaphiliac** [comment]
Timothy Younger, American Express

**Comment by robmoffat** [comment]
# February 15, 2023

Attendees: Refer to GitHub Issues for meeting agenda [LINK](https://github.com/finos/open-source-readiness/issues/85)

Scribe: Cara Delia,

Squire: Rob Moffat


## Meeting Notes/Action Items - 2/15/2023:



* Discussed PR https://github.com/finos/open-source-readiness/pull/89
* What do we need in the document for the personas? There is a doc on Risk, OSPO, Developer
* Brittany discussed personas need to be based on maturity levels and applying to the personas. Use experiential knowledge to base on the personas motivations and needs. Phased approach recommended- Novice to Advance +1 Elspeth agreed
* Need to separate the roles from org maturity (Andrew) Not 1:1 maturity for say a compliance/legal role
* Let’s take one persona (Developer) to see how applicable and what needs to be included/revised

<table>
  <tr>
   <td>
OS Maturity Level
   </td>
   <td>Engagement:
<p>
ISPO/OSPO
   </td>
   <td><strong>Developer</strong>
   </td>
   <td>Responsibilities
   </td>
   <td>Encouraged Activities/Potential OKRs
   </td>
  </tr>
  <tr>
   <td>1 
   </td>
   <td>ISPO
   </td>
   <td>Entry Level, may have components of open source but not aware using
   </td>
   <td>
   </td>
   <td>
   </td>
  </tr>
  <tr>
   <td>2 
   </td>
   <td>ISPO
   </td>
   <td>Understand the firms’ governance, policies, and processes of how to leverage OSS. 
   </td>
   <td>Approved to leverage open source and pulling in dependency in their projects.
<p>
Understanding OSS Licenses from a consumption perspective
   </td>
   <td>Share process of leveraging open source with others
<p>
Have own profile and develop in personal repos. 
<p>
Experimenting more with OSS outside of work.
<p>
Understand <em>permissions </em>granted by an OSS License
   </td>
  </tr>
  <tr>
   <td>3 
   </td>
   <td>ISPO/OSPO
   </td>
   <td>Knowledge of open source and understand and see where code needs fixing.
   </td>
   <td>Might be maintaining internal forks of external projects
<p>
Fixing a bug in an open source project and
<p>
Understanding OSS Licenses from the perspective of contributing
   </td>
   <td>Understand <em>conditions </em>of OSS Licenses
   </td>
  </tr>
  <tr>
   <td>4
   </td>
   <td>OSPO
   </td>
   <td>Contributing not just consuming
   </td>
   <td>Invested in OSS community.Contributing a whole open source project, contributing back to open issues
   </td>
   <td>To have them differentiated to receive budget
<p>
Understand <em>limiitations </em>of OSS License
   </td>
  </tr>
  <tr>
   <td>5  
   </td>
   <td>OSPO
   </td>
   <td>outside maintainer, contributed project on behalf of company.  Has OSS work scoped into their role, participation in community and externally
   </td>
   <td>Seen as OSS SME
<p>
Maintaining an open source project
<p>
Understanding and getting started with patents. 
<p>
Proactively and strategically leverage OSS licensing models
   </td>
   <td>Community Engagement/ Public Speaking/Content (Blogs, etc)
<p>
To receive budget
   </td>
  </tr>
</table>
