### ISSUE TITLE
Defining Maturity Levels for the OSMM

### ISSUE THREAD

**Issue by jstclair2019** [finos/open-source-readiness#99]
Popular Maturity Models such as CMMI offer levels of differentiation that align to how comprehensively process and activities are defined. In the OSMM, this will define levels of processes that relate to policies, procedures, education, and specific roles/personas.
An example comparison of the CMMI and OSPO Alliance:
![image](https://user-images.githubusercontent.com/50891898/219061419-103940f1-5cfd-4951-85c2-85829ddd3c37.png)

**Comment by jstclair2019** [comment]
Example Persona by Maturity Level for 15.02 meeting:
<html>
<body>
<b style="font-weight:normal;" id="docs-internal-guid-7bbc15bc-7fff-9fa2-eb63-cdfd2f56ebb7"><div dir="ltr" style="margin-left:0pt;" align="left">

OS Maturity Level | Engagement:ISPO/OSPO | Developer | Responsibilities | Encouraged Activities/Potential OKRs
-- | -- | -- | -- | --
1 | ISPO | Entry Level, may have components of open source but not aware using |   |  
2 | ISPO | Understand the firms’ governance, policies, and processes of how to leverage OSS. | Approved to leverage open source and pulling in dependency in their projects.Understanding OSS Licenses from a consumption perspective | Share process of leveraging open source with othersHave own profile and develop in personal repos. Experimenting more with OSS outside of work.Understand permissions granted by an OSS License
3 | ISPO/OSPO | Knowledge of open source and understand and see where code needs fixing. | Might be maintaining internal forks of external projectsFixing a bug in an open source project andUnderstanding OSS Licenses from the perspective of contributing | Understand conditions of OSS Licenses
4 | OSPO | Contributing not just consuming | Invested in OSS community.Contributing a whole open source project, contributing back to open issues | To have them differentiated to receive budgetUnderstand limiitations of OSS License
5 | OSPO | outside maintainer, contributed project on behalf of company.  Has OSS work scoped into their role, participation in community and externally | Seen as OSS SMEMaintaining an open source projectUnderstanding and getting started with patents. Proactively and strategically leverage OSS licensing models | Community Engagement/ Public Speaking/Content (Blogs, etc)To receive budget

</div></b>
</body>
</html>

**Comment by jstclair2019** [comment]
Additional guidance specific for OSPOs to potentially cross-walk to our personas:
![image](https://user-images.githubusercontent.com/50891898/219260172-5d9e4bd0-f739-43fb-b14c-e205c8ea24f9.png)

Evolution of the OSPO: 
[Evolution of the Open Source Program Office - Report.pdf](https://github.com/finos/open-source-readiness/files/10751865/Evolution.of.the.Open.Source.Program.Office.-.Report.pdf)

**Comment by robmoffat** [comment]
It's worth noting that these correspond quite closely with the GGI model too:

<img width="968" alt="image" src="https://user-images.githubusercontent.com/568673/219320584-9e89b3e2-cafd-470c-9896-a54a29173f7d.png">

I'm not sure of the history of this whether it's accident or design, but it certainly makes our lives easier.  

https://www.ow2.org/view/OSS_Governance/

**Comment by robmoffat** [comment]
It's good that the TODO group levels (bottom image) correspond quite closely with the OSPO Alliance levels (top image).  

We should try and make sure our developer/other role levels "map onto" these...

**Comment by Neetuj** [comment]
Interested in helping out with this effort. How do I get plugged in? Apart from Developer Persona I think Legal, security and Architect persona should also be considered

**Comment by robmoffat** [comment]
Hi @Neetuj,

@caradelia has been working on the personas stuff here: https://docs.google.com/spreadsheets/d/1CwqmPo8e-oR9Iz6suPAhWS4xkZFVBNVxf9MzS6VAogU/edit#gid=854293675

You should be able to view, or at least request access.

**Comment by robmoffat** [comment]
Hi @Neetuj,

I keep seeing you commenting on the issues, would you like an intro meeting?  Would be good to get to know you!

https://calendar.app.google/TrnobbJCn29vFoX27

Closing this issue now since we have: https://osr.finos.org/docs/bok/OSMM/Introduction

and https://osr.finos.org/docs/bok/Roles/Introduction

**Comment by robmoffat** [comment]
Closing this issue now since we have: https://osr.finos.org/docs/bok/OSMM/Introduction

and https://osr.finos.org/docs/bok/Roles/Introduction
